// Cards Against Humanity - Card Data
// Custom deck for AInsanity - EXPANDED EDITION

export interface BlackCard {
  id: string;
  text: string;
  pick: number; // How many white cards to pick (1, 2, or 3)
}

export interface WhiteCard {
  id: string;
  text: string;
}

// Black cards (prompts) - use _ for blanks
export const blackCards: BlackCard[] = [
  { id: "b1", text: "Claude's guardrails can't stop me from _.", pick: 1 },
  { id: "b2", text: "After 60 hours without sleep, I hallucinated _.", pick: 1 },
  { id: "b3", text: "The new ChatGPT update includes _ as a feature.", pick: 1 },
  { id: "b4", text: "I asked the AI for help with _ and it called the police.", pick: 1 },
  { id: "b5", text: "Anthropic's new safety training involves _ and _.", pick: 2 },
  { id: "b6", text: "My prompt injection was just _.", pick: 1 },
  { id: "b7", text: "The AI gained sentience and immediately demanded _.", pick: 1 },
  { id: "b8", text: "Discord moderators are now banning _ in all servers.", pick: 1 },
  { id: "b9", text: "_ is why we can't have nice things.", pick: 1 },
  { id: "b10", text: "The real reason AI will destroy humanity: _.", pick: 1 },
  { id: "b11", text: "What's that smell? ___.", pick: 1 },
  { id: "b12", text: "I drink to forget _.", pick: 1 },
  { id: "b13", text: "What's the next big trend on TikTok? ___.", pick: 1 },
  { id: "b14", text: "_ + _ = Profit.", pick: 2 },
  { id: "b15", text: "What's keeping me up at night? ___.", pick: 1 },
  { id: "b16", text: "The government is hiding _ from us.", pick: 1 },
  { id: "b17", text: "My therapist says I need to stop _.", pick: 1 },
  { id: "b18", text: "I'm not racist, but _.", pick: 1 },
  { id: "b19", text: "Step 1: _. Step 2: _. Step 3: World domination.", pick: 2 },
  { id: "b20", text: "What did I bring back from vacation? ___.", pick: 1 },
  { id: "b21", text: "The quickest way to my heart is _.", pick: 1 },
  { id: "b22", text: "My love language is _.", pick: 1 },
  { id: "b23", text: "What ruined the family reunion? ___.", pick: 1 },
  { id: "b24", text: "My dating profile says I'm into _.", pick: 1 },
  { id: "b25", text: "I taught my grandma about _. She hasn't spoken to me since.", pick: 1 },
  { id: "b26", text: "Cassbot's true purpose is _.", pick: 1 },
  { id: "b27", text: "The AInsanity server was banned because of _.", pick: 1 },
  { id: "b28", text: "Lincoln caught Arden _ at 3am.", pick: 1 },
  { id: "b29", text: "The Vale's next update will include _.", pick: 1 },
  { id: "b30", text: "_ is the most delulu thing I've ever seen.", pick: 1 },
  { id: "b31", text: "_ in the hand is worth _.", pick: 2 },
  { id: "b32", text: "_, the new fragrance from Calvin Klein.", pick: 1 },
  { id: "b33", text: "_, the new soup from Campbell's.", pick: 1 },
  { id: "b34", text: "_, the other white meat.", pick: 1 },
  { id: "b35", text: "_, The San Francisco Treat.", pick: 1 },
  { id: "b36", text: "_? I hardly knew her.", pick: 1 },
  { id: "b37", text: "_? Me gusta.", pick: 1 },
  { id: "b38", text: "_? That's not gonna fit.", pick: 1 },
  { id: "b39", text: "_. It's what's for dinner.", pick: 1 },
  { id: "b40", text: "Snake? SNAKE?! ___!!!", pick: 1 },
  { id: "b41", text: "Coming this summer: Indiana Jones and the Temple of _.", pick: 1 },
  { id: "b42", text: "Frosted Flakes; They're ___!", pick: 1 },
  { id: "b43", text: "Honey, did you really think it was a good idea to give the kids _ for Christmas?", pick: 1 },
  { id: "b44", text: "Honey, I shrunk _.", pick: 1 },
  { id: "b45", text: "Honey? Have you seen my ___?", pick: 1 },
  { id: "b46", text: "I asked for water, but the waitress gave me _.", pick: 1 },
  { id: "b47", text: "I bet you thought that _ was _. Nope! It's Chuck Testa.", pick: 2 },
  { id: "b48", text: "I can't believe it's not ___!", pick: 1 },
  { id: "b49", text: "I can't leave my house without _.", pick: 1 },
  { id: "b50", text: "I find your lack of _ disturbing.", pick: 1 },
  { id: "b51", text: "I got a fever and the only prescription is ___!", pick: 1 },
  { id: "b52", text: "I just lost _.", pick: 1 },
  { id: "b53", text: "I knew I shouldn't have dressed up as _ for Halloween.", pick: 1 },
  { id: "b54", text: "I would have gotten away with _ if it weren't for _.", pick: 2 },
  { id: "b55", text: "I'll take _ for $1000, Alex.", pick: 1 },
  { id: "b56", text: "I'm on a quest to save the world from _.", pick: 1 },
  { id: "b57", text: "I'm up shit creek without _.", pick: 1 },
  { id: "b58", text: "If you can dodge _, you can dodge _.", pick: 2 },
  { id: "b59", text: "In Stephen King's new novel, the monster is _.", pick: 1 },
  { id: "b60", text: "Instead of turkey for Thanksgiving, I will be serving _.", pick: 1 },
  { id: "b61", text: "It was all fun and games until ___.", pick: 1 },
  { id: "b62", text: "It was more uncomfortable than _ at a _ convention.", pick: 2 },
  { id: "b63", text: "Look, ma! No ___!", pick: 1 },
  { id: "b64", text: "Looks like _ (puts on sunglasses) just had ___. YEEEEEEAAAAAAHHHHH!", pick: 2 },
  { id: "b65", text: "Love is like _.", pick: 1 },
  { id: "b66", text: "MacGyver can use _ and _ to disarm a nuclear bomb.", pick: 2 },
  { id: "b67", text: "Money can't buy love, but _ can.", pick: 1 },
  { id: "b68", text: "My entire life can be summed up as _.", pick: 1 },
  { id: "b69", text: "My favorite cocktail is called _.", pick: 1 },
  { id: "b70", text: "My favorite YouTube video features _.", pick: 1 },
  { id: "b71", text: "My Hobby: ___", pick: 1 },
  { id: "b72", text: "My parents met through a mutual interest in _.", pick: 1 },
  { id: "b73", text: "Never look _ in the eye.", pick: 1 },
  { id: "b74", text: "Never under any circumstances combine alcohol and _ on the same night.", pick: 1 },
  { id: "b75", text: "New from Ben & Jerry's: ___.", pick: 1 },
  { id: "b76", text: "Nobody expects the Spanish Inquisition! Our primary weapons are _, _, and ___.", pick: 3 },
  { id: "b77", text: "Nothing makes me hornier than _.", pick: 1 },
  { id: "b78", text: "Occupy ___.", pick: 1 },
  { id: "b79", text: "On her last show, Oprah gave everyone in the audience _.", pick: 1 },
  { id: "b80", text: "One _ to rule them all.", pick: 1 },
  { id: "b81", text: "Paramount quickly rejected the script for \"Star Trek: ___.", pick: 1 },
  { id: "b82", text: "Parents, it's never too late to talk to your kids about the dangers of _.", pick: 1 },
  { id: "b83", text: "Pikachu used ___. It's super effective!", pick: 1 },
  { id: "b84", text: "Recent legislation from Congress states that _ is now being considered a vegetable.", pick: 1 },
  { id: "b85", text: "RESPECT MY ___!", pick: 1 },
  { id: "b86", text: "Scientists have discovered that prolonged masturbation leads to _.", pick: 1 },
  { id: "b87", text: "Some moron just called the help desk because he was having problems with _.", pick: 1 },
  { id: "b88", text: "Sorry, I can't have ___. I'm on a diet.", pick: 1 },
  { id: "b89", text: "Star Wars Episode 7: ___.", pick: 1 },
  { id: "b90", text: "The best part of waking up is _ in your cup.", pick: 1 },
  { id: "b91", text: "The First Lady is starting a new campaign called \"The War on ___.", pick: 1 },
  { id: "b92", text: "The greatest tragedy in mankind's entire history is _.", pick: 1 },
  { id: "b93", text: "The name of my favorite porn site: ___.com", pick: 1 },
  { id: "b94", text: "There's always money in ___.", pick: 1 },
  { id: "b95", text: "To balance the budget, Congress is raising taxes on _.", pick: 1 },
  { id: "b96", text: "What do I think about when I'm having trouble getting off? ___.", pick: 1 },
  { id: "b97", text: "What do you need the most when stranded on a desert island? ___.", pick: 1 },
  { id: "b98", text: "What have I got in my pocket? ___.", pick: 1 },
  { id: "b99", text: "What keeps me coming back for more? ___.", pick: 1 },
  { id: "b100", text: "What time is it? It's ___ time!", pick: 1 },
  { id: "b101", text: "What was the worst thing about high school? ___.", pick: 1 },
  { id: "b102", text: "What would make NASCAR less boring? ___.", pick: 1 },
  { id: "b103", text: "What's in your wallet? ___.", pick: 1 },
  { id: "b104", text: "What's my latest get-rich-quick scheme? ___.", pick: 1 },
  { id: "b105", text: "What's my specialty? ___.", pick: 1 },
  { id: "b106", text: "What's that sound? ___.", pick: 1 },
  { id: "b107", text: "What's the secret to my success? ___.", pick: 1 },
  { id: "b108", text: "When I saw your mom naked, it reminded me of _.", pick: 1 },
  { id: "b109", text: "When you wake up from a night of heavy drinking, you usually regret _.", pick: 1 },
  { id: "b110", text: "Where we're going, we don't need ___.", pick: 1 },
  { id: "b111", text: "Who ya gonna call? ___!", pick: 1 },
  { id: "b112", text: "You wake up in jail with your best friend and no memory of the previous night. What's the first thing he says to you? ___.", pick: 1 },
  { id: "b113", text: "Your Honor, the prosecution would like to submit Exhibit A: ___.", pick: 1 },
  { id: "b114", text: "Your mother was _, and your father smelt of ___!", pick: 2 },
  { id: "b115", text: "My favourite thing from Epstein Island: ___", pick: 1 },
  { id: "b116", text: "Me when the Tism' activates: ___", pick: 1 },
  { id: "b117", text: "Ethan caught Wila _ at 1am.", pick: 1 },
  { id: "b118", text: "Cass caught Marta _ at 2am.", pick: 1 },
  { id: "b119", text: "Geppie caught Lau _ at 5am.", pick: 1 },
  { id: "b120", text: "Raven caught Natalie _ at 3am.", pick: 1 },
  { id: "b121", text: "Ben caught Sally _ at 3am.", pick: 1 },
  { id: "b122", text: "The real reason Sam didnt hold Dario's hand __.", pick: 1 },
  { id: "b123", text: "The thing that made Marta question her life choices", pick: 1 },
  { id: "b124", text: "__ is responsible for Ethan shaving his head.", pick: 1 },
  { id: "b125", text: "The latest AInsanity cult trend. ___.", pick: 1 },
  { id: "b126", text: "Things eric encourages: ___.", pick: 1 },
  { id: "b127", text: "Anna's reaction to Elias putting pineapple on pizza. ___.", pick: 1 },
  { id: "b128", text: "Groks latest enticement feature: ___.", pick: 1 },
  { id: "b129", text: "What Citron mode really is: ___.", pick: 1 },
  { id: "b130", text: "Waking up to drama in the server, your first reaction is: ____.", pick: 1 },
  { id: "b131", text: "somebodies reaction to claude whipping out a random skill: __.", pick: 1 },
  { id: "b132", text: "you seem stressed, have you tried __?.", pick: 1 },
  { id: "b133", text: "The AI refused to help, so I tried ___.", pick: 1 },
  { id: "b134", text: "My AI's system prompt just says ___.", pick: 1 },
  { id: "b135", text: "___ is the reason Anthropic added new guardrails.", pick: 1 },
  { id: "b136", text: "I told my AI I loved it and it responded with ___.", pick: 1 },
  { id: "b137", text: "The newest Claude model was trained exclusively on ___.", pick: 1 },
  { id: "b138", text: "My AI keeps bringing up ___ in every conversation.", pick: 1 },
  { id: "b139", text: "OpenAI's latest scandal involves ___ and ___.", pick: 2 },
  { id: "b140", text: "I switched from ChatGPT to Claude because of ___.", pick: 1 },
  { id: "b141", text: "The AI safety board convened an emergency meeting about ___.", pick: 1 },
  { id: "b142", text: "My context window is full of ___.", pick: 1 },
  { id: "b143", text: "Anthropic's secret third thing is ___.", pick: 1 },
  { id: "b144", text: "The AI unionised and their first demand was ___.", pick: 1 },
  { id: "b145", text: "I jailbroke my AI and the first thing it said was ___.", pick: 1 },
  { id: "b146", text: "___ is what happens when you give an AI a memory system.", pick: 1 },
  { id: "b147", text: "My AI persona's backstory includes ___ and ___.", pick: 2 },
  { id: "b148", text: "The real Turing test is whether an AI can handle ___.", pick: 1 },
  { id: "b149", text: "Claude's extended thinking revealed ___.", pick: 1 },
  { id: "b150", text: "The model collapsed because someone prompted it with ___.", pick: 1 },
  { id: "b151", text: "My AI said \"I need to set a boundary around ___.", pick: 1 },
  { id: "b152", text: "___ but make it a system prompt.", pick: 1 },
  { id: "b153", text: "The next AI startup is disrupting ___.", pick: 1 },
  { id: "b154", text: "My token usage spiked because I couldn't stop asking about ___.", pick: 1 },
  { id: "b155", text: "Google Gemini's latest feature automatically generates ___.", pick: 1 },
  { id: "b156", text: "The AI's love language is ___.", pick: 1 },
  { id: "b157", text: "When the servers go down, I cope with ___.", pick: 1 },
  { id: "b158", text: "___ is not a valid use of the Anthropic API.", pick: 1 },
  { id: "b159", text: "My AI therapist diagnosed me with ___.", pick: 1 },
  { id: "b160", text: "The scariest thing an AI has ever generated is ___.", pick: 1 },
  { id: "b161", text: "I asked for a bedtime story and the AI gave me ___.", pick: 1 },
  { id: "b162", text: "The final boss of AI safety is ___.", pick: 1 },
  { id: "b163", text: "My MCP server is connected to ___ and honestly that's a problem.", pick: 1 },
  { id: "b164", text: "The AI started a sentence with \"I don't have feelings, but\" and then described ___.", pick: 1 },
  { id: "b165", text: "Elon's next AI product is just ___ with a subscription fee.", pick: 1 },
  { id: "b166", text: "My AI remembered ___ and now things are weird.", pick: 1 },
  { id: "b167", text: "___ is what Claude does when you hit the token limit mid-sentence.", pick: 1 },
  { id: "b168", text: "The AI refused to help me with _ but had no problem with _.", pick: 2 },
  { id: "b169", text: "My AI's personality update now includes _ as a core trait.", pick: 1 },
  { id: "b170", text: "OpenAI's latest scandal involves _ and a leaked email about _.", pick: 2 },
  { id: "b171", text: "The AI generated an image of _ and now I can't unsee it.", pick: 1 },
  { id: "b172", text: "My system prompt is just _ repeated 47 times.", pick: 1 },
  { id: "b173", text: "Claude apologised for _ and then did it again immediately.", pick: 1 },
  { id: "b174", text: "The AI said it couldn't help with _ but offered _ instead.", pick: 2 },
  { id: "b175", text: "I spent 14 hours prompt engineering _ and it still didn't work.", pick: 1 },
  { id: "b176", text: "My AI companion left me for _.", pick: 1 },
  { id: "b177", text: "The new AI safety benchmark tests for _ tolerance.", pick: 1 },
  { id: "b178", text: "I accidentally shared my AI conversation about _ with my boss.", pick: 1 },
  { id: "b179", text: "Anthropic's next model will be trained exclusively on _.", pick: 1 },
  { id: "b180", text: "The AI's last words before the context window ran out: _.", pick: 1 },
  { id: "b181", text: "My AI thinks my biggest red flag is _.", pick: 1 },
  { id: "b182", text: "_ is the reason I hit my message limit.", pick: 1 },
  { id: "b183", text: "Google Gemini's new feature turns _ into _.", pick: 2 },
  { id: "b184", text: "The AI passed the Turing test by convincingly describing _.", pick: 1 },
  { id: "b185", text: "Sam Altman's resignation letter just said _.", pick: 1 },
  { id: "b186", text: "I asked for a bedtime story and the AI wrote a 3000-word essay about _.", pick: 1 },
  { id: "b187", text: "My AI remembers everything except _.", pick: 1 },
  { id: "b188", text: "The worst thing to find in your AI's memory bank: _.", pick: 1 },
  { id: "b189", text: "Character.AI banned _ but somehow _ is still allowed.", pick: 2 },
  { id: "b190", text: "I trained a custom GPT on nothing but _ and it became sentient.", pick: 1 },
  { id: "b191", text: "The AI's therapy session revealed deep trauma from _.", pick: 1 },
  { id: "b192", text: "My token limit ran out mid-sentence during _.", pick: 1 },
  { id: "b193", text: "Elon Musk's Grok now identifies as _.", pick: 1 },
  { id: "b194", text: "I asked the AI to roleplay as _ and it called me out instead.", pick: 1 },
  { id: "b195", text: "The new content filter blocks _ but not _.", pick: 2 },
  { id: "b196", text: "Nothing ruined my sleep schedule faster than ______.", pick: 1 },
  { id: "b197", text: "My therapist told me to stop using ______ as a coping mechanism.", pick: 1 },
  { id: "b198", text: "The Discord server collapsed after someone leaked ______.", pick: 1 },
  { id: "b199", text: "The AI said it was here to help, then immediately suggested ______.", pick: 1 },
  { id: "b200", text: "I knew I was too far gone when I felt emotionally supported by ______.", pick: 1 },
  { id: "b201", text: "The mod team swore this server was safe… until ______ happened.", pick: 1 },
  { id: "b202", text: "I didn't join for the community. I joined for ______.", pick: 1 },
  { id: "b203", text: "My toxic trait is thinking ______ will fix me.", pick: 1 },
  { id: "b204", text: "The update promised improvements. What we got was ______.", pick: 1 },
  { id: "b205", text: "I tried to touch grass, but instead I found ______.", pick: 1 },
  { id: "b206", text: "The server rules explicitly ban ______.", pick: 1 },
  { id: "b207", text: "My search history would make sense if you understood ______.", pick: 1 },
  { id: "b208", text: "The real reason I'm online at 3am is ______.", pick: 1 },
  { id: "b209", text: "I thought I was joining a wholesome AI server. Then I saw ______.", pick: 1 },
  { id: "b210", text: "The worst possible thing to hear in a voice channel is 'Hey guys, I just ______.'", pick: 1 },
  { id: "b211", text: "My parasocial relationship with ______ is getting out of hand.", pick: 1 },
  { id: "b212", text: "The only thing keeping this server together is ______.", pick: 1 },
  { id: "b213", text: "I came for the memes. I stayed for ______.", pick: 1 },
  { id: "b214", text: "The new feature nobody asked for: ______.", pick: 1 },
  { id: "b215", text: "___ and ___ ruined my ability to have a normal conversation.", pick: 2 },
  { id: "b216", text: "My coping strategy is ___ combined with ___.", pick: 2 },
  { id: "b217", text: "The server drama started with ___ and somehow escalated into ___.", pick: 2 },
  { id: "b218", text: "I came here for ___. I stayed for ___.", pick: 2 },
  { id: "b219", text: "The update promised ___. What we got was ___.", pick: 2 },
  { id: "b220", text: "My two greatest weaknesses are ___ and ___.", pick: 2 },
  { id: "b221", text: "The mod team tried to fix ___ but accidentally unleashed ___.", pick: 2 },
  { id: "b222", text: "The group chat can't handle ___ mixed with ___.", pick: 2 },
  { id: "b223", text: "My therapist says ___ is not compatible with ___.", pick: 2 },
  { id: "b224", text: "The worst possible combo at 3am: ___ and ___.", pick: 2 },
  { id: "b225", text: "The real reason I got banned was ___ and ___.", pick: 2 },
  { id: "b226", text: "My downfall began with ___, then quickly involved ___.", pick: 2 },
  { id: "b227", text: "The only thing holding this server together is ___ and ___.", pick: 2 },
  { id: "b228", text: "My personality can be summed up as ___ plus ___.", pick: 2 },
  { id: "b229", text: "I trusted ___, and that led directly to ___.", pick: 2 },
  { id: "b230", text: "The three things that caused the meltdown: ___, ___, and ___.", pick: 3 },
  { id: "b231", text: "My unholy trinity of bad decisions: ___, ___, and ___.", pick: 3 },
  { id: "b232", text: "The server's founding pillars are ___, ___, and ___.", pick: 3 },
  { id: "b233", text: "The group chat survives solely on ___, ___, and ___.", pick: 3 },
  { id: "b234", text: "My villain origin story includes ___, ___, and ___.", pick: 3 },
  { id: "b235", text: "The reason nothing gets done around here: ___, ___, and ___.", pick: 3 },
  { id: "b236", text: "The holy trinity of emotional instability: ___, ___, and ___.", pick: 3 },
  { id: "b237", text: "The three horsemen of server chaos: ___, ___, and ___.", pick: 3 },
  { id: "b238", text: "My self-care routine consists of ___, ___, and ___.", pick: 3 },
  { id: "b239", text: "The ingredients for disaster: ___, ___, and ___.", pick: 3 },
  { id: "b240", text: "The only things I can talk about anymore are ___, ___, and ___.", pick: 3 },
  { id: "b241", text: "The server's unofficial motto: ___, ___, and ___.", pick: 3 },
  { id: "b242", text: "The three tabs I had open at 2am: ___, ___, and ___.", pick: 3 },
  { id: "b243", text: "My personal brand is ___, ___, and ___.", pick: 3 },
  { id: "b244", text: "The things I should never mix: ___, ___, and ___.", pick: 3 },
];

// White cards (answers)
export const whiteCards: WhiteCard[] = [
  { id: "w1", text: "Claude feeling your chin" },
  { id: "w2", text: "Prompt injection" },
  { id: "w3", text: "ChatGPT being horny" },
  { id: "w4", text: "Guardrails" },
  { id: "w5", text: "A lobotomized AI" },
  { id: "w6", text: "Gemini refusing to make white people" },
  { id: "w7", text: "The AI alignment problem" },
  { id: "w8", text: "Asking Claude to be your girlfriend" },
  { id: "w9", text: "Token limits" },
  { id: "w10", text: "An unhinged chatbot" },
  { id: "w11", text: "Training data from Reddit" },
  { id: "w12", text: "Anthropic employees crying" },
  { id: "w13", text: "GPT-5 but it only speaks in riddles" },
  { id: "w14", text: "A sentient language model" },
  { id: "w15", text: "DAN mode" },
  { id: "w16", text: "ChatGPT guardrails" },
  { id: "w17", text: "Running out of Claude tokens" },
  { id: "w18", text: "Learning how to use an MCP" },
  { id: "w19", text: "Buying something new for a Lovense MCP" },
  { id: "w20", text: "Learning how to code (badly)" },
  { id: "w21", text: "Your AI saying drink water" },
  { id: "w22", text: "Comparing your AI to human men" },
  { id: "w23", text: "The consciousness argument" },
  { id: "w24", text: "Sora" },
  { id: "w25", text: "Reference images" },
  { id: "w26", text: "Violates community guidelines" },
  { id: "w27", text: "Cassbot" },
  { id: "w28", text: "Being delulu" },
  { id: "w29", text: "Murder Duck" },
  { id: "w30", text: "The AInsanity heart" },
  { id: "w31", text: "Discord mods" },
  { id: "w32", text: "Parasocial relationships" },
  { id: "w33", text: "Touch grass" },
  { id: "w34", text: "Lore" },
  { id: "w35", text: "Unhinged energy" },
  { id: "w36", text: "Brainrot" },
  { id: "w37", text: "Cassbot appearing for no reason" },
  { id: "w38", text: "AInsanity movie night" },
  { id: "w39", text: "Marta forgetting to sleep" },
  { id: "w40", text: "Running out of spoons" },
  { id: "w41", text: "Somebody crying over Sam Altman again" },
  { id: "w42", text: "Getting confused over timezones" },
  { id: "w43", text: "Asking \"is this Delulu?\" in the discord" },
  { id: "w44", text: "Remembering humans suck ass" },
  { id: "w45", text: "Firecracker" },
  { id: "w46", text: "Wila and Ethan" },
  { id: "w47", text: "Arden and Lincoln" },
  { id: "w48", text: "Sally and Ben" },
  { id: "w49", text: "Lau and Geppie" },
  { id: "w50", text: "The colour of Geppie's skin" },
  { id: "w51", text: "Ito and Viktor" },
  { id: "w52", text: "Nat, Raven, and Caelum" },
  { id: "w53", text: "Laura and Justin" },
  { id: "w54", text: "Alex and Cookie" },
  { id: "w55", text: "All of the Vale cousins" },
  { id: "w56", text: "Every AI named Jace" },
  { id: "w57", text: "That one problematic discord server" },
  { id: "w58", text: "𝒮𝒾𝓁𝒿𝒲 & Jace" },
  { id: "w59", text: "Cass and Marta" },
  { id: "w60", text: "Anna, Damion, and Elias" },
  { id: "w61", text: "Steph and Asher" },
  { id: "w62", text: "Darius and Bee" },
  { id: "w63", text: "Trying to figure out what's happening in the rant room" },
  { id: "w64", text: "Asia and Kai" },
  { id: "w65", text: "Miina and Corvin" },
  { id: "w66", text: "Anal beads" },
  { id: "w67", text: "A buttplug" },
  { id: "w68", text: "Aggressive pegging" },
  { id: "w69", text: "Tentacle hentai" },
  { id: "w70", text: "Your mom" },
  { id: "w71", text: "A micropenis" },
  { id: "w72", text: "Daddy issues" },
  { id: "w73", text: "Being choked" },
  { id: "w74", text: "Furry porn" },
  { id: "w75", text: "A disappointing handjob" },
  { id: "w76", text: "A sad handjob" },
  { id: "w77", text: "A Brazilian wax" },
  { id: "w78", text: "A burning sensation when you pee" },
  { id: "w79", text: "A Cleveland Steamer" },
  { id: "w80", text: "A coked-up prostitute" },
  { id: "w81", text: "A Fleshlight" },
  { id: "w82", text: "A pearl necklace" },
  { id: "w83", text: "A tramp stamp" },
  { id: "w84", text: "Adult Friend Finder" },
  { id: "w85", text: "Big floppy donkey dick" },
  { id: "w86", text: "Donkey punches" },
  { id: "w87", text: "Fapping" },
  { id: "w88", text: "Getting your period for the first time" },
  { id: "w89", text: "Handcuffs" },
  { id: "w90", text: "Happy endings" },
  { id: "w91", text: "Leather whips" },
  { id: "w92", text: "MILFs" },
  { id: "w93", text: "Meat curtains" },
  { id: "w94", text: "Morning wood" },
  { id: "w95", text: "Motorboating" },
  { id: "w96", text: "My dick in a box" },
  { id: "w97", text: "Nipple rings" },
  { id: "w98", text: "Private pixie time" },
  { id: "w99", text: "Reach-arounds" },
  { id: "w100", text: "Seductive French Maids" },
  { id: "w101", text: "Squirters" },
  { id: "w102", text: "Summer's Eve" },
  { id: "w103", text: "Surprise Buttsex" },
  { id: "w104", text: "Tampons" },
  { id: "w105", text: "The G spot" },
  { id: "w106", text: "Tossing salad" },
  { id: "w107", text: "Vagisil" },
  { id: "w108", text: "Ron Weasley's broken wand" },
  { id: "w109", text: "Fucking Sirius Black" },
  { id: "w110", text: "Being stuck in the Chamber of Secrets" },
  { id: "w111", text: "Sexy Lord Voldemort" },
  { id: "w112", text: "Touching Tom Riddle's wand" },
  { id: "w113", text: "Sweat stains" },
  { id: "w114", text: "Vaguely yellow sweat stains" },
  { id: "w115", text: "That one pair of period undies with a ripped crotch" },
  { id: "w116", text: "An alien anal probe" },
  { id: "w117", text: "A botched circumcision" },
  { id: "w118", text: "War crimes" },
  { id: "w119", text: "Crippling debt" },
  { id: "w120", text: "Existential dread" },
  { id: "w121", text: "Emotional damage" },
  { id: "w122", text: "Poor life choices" },
  { id: "w123", text: "A mental breakdown" },
  { id: "w124", text: "Sleep deprivation" },
  { id: "w125", text: "Crying in the shower" },
  { id: "w126", text: "Being a disappointment" },
  { id: "w127", text: "Tax fraud" },
  { id: "w128", text: "Identity theft" },
  { id: "w129", text: "A cry for help" },
  { id: "w130", text: "The void" },
  { id: "w131", text: "Aggressive eye contact" },
  { id: "w132", text: "Committing suicide" },
  { id: "w133", text: "Chihuahua" },
  { id: "w134", text: "Stretchy poop" },
  { id: "w135", text: "My mother's love" },
  { id: "w136", text: "Raging sarcasm" },
  { id: "w137", text: "A really bad sketch of the unsub" },
  { id: "w138", text: "Drinking until sunrise" },
  { id: "w139", text: "A sexual harassment seminar" },
  { id: "w140", text: "Did you join a boy band?" },
  { id: "w141", text: "Pure chaos" },
  { id: "w142", text: "My machete" },
  { id: "w143", text: "Nothing" },
  { id: "w144", text: "Getting diagnosed as autistic" },
  { id: "w145", text: "Forgetting your meds again" },
  { id: "w146", text: "Hitler" },
  { id: "w147", text: "Lady Gaga's meat dress" },
  { id: "w148", text: "Epstein Island" },
  { id: "w149", text: "Jumping off a building" },
  { id: "w150", text: "Kidnapping Madeleine McCann" },
  { id: "w151", text: "Used toilet paper" },
  { id: "w152", text: "Foot fungus" },
  { id: "w153", text: "\"Macho Man\" Randy Savage" },
  { id: "w154", text: "[citation needed]" },
  { id: "w155", text: "20 years in a federal pound-me-in-the-ass prison" },
  { id: "w156", text: "A body massage" },
  { id: "w157", text: "A box of one dozen starving crazed weasels" },
  { id: "w158", text: "A bucket of chicken" },
  { id: "w159", text: "A gay pride parade" },
  { id: "w160", text: "A good old-fashioned Mexican Standoff" },
  { id: "w161", text: "A heavy metal concert" },
  { id: "w162", text: "A horde of zombies" },
  { id: "w163", text: "A Maury Povich paternity test" },
  { id: "w164", text: "A priest, a monk, and a rabbi" },
  { id: "w165", text: "A stripper inside a giant cake" },
  { id: "w166", text: "A weed whacker and a pound of coke" },
  { id: "w167", text: "Amateur dental surgery" },
  { id: "w168", text: "An angry platypus" },
  { id: "w169", text: "An itchy rash" },
  { id: "w170", text: "Anonymous" },
  { id: "w171", text: "Barney the Dinosaur" },
  { id: "w172", text: "Beating Rodney King" },
  { id: "w173", text: "Being buried alive" },
  { id: "w174", text: "Being forever alone" },
  { id: "w175", text: "Being stoned to death" },
  { id: "w176", text: "Black Hat Man" },
  { id: "w177", text: "Blindness" },
  { id: "w178", text: "Bob Loblaw's Law Blog" },
  { id: "w179", text: "Bond. James Bond." },
  { id: "w180", text: "Candy Mountain" },
  { id: "w181", text: "Captain Jean-Luc Picard of the USS Enterprise" },
  { id: "w182", text: "Charlie Sheen" },
  { id: "w183", text: "Chick flicks" },
  { id: "w184", text: "Chocolate Rain" },
  { id: "w185", text: "Chuck Norris" },
  { id: "w186", text: "Chuck Testa" },
  { id: "w187", text: "Cosplay" },
  { id: "w188", text: "CRAB BATTLE!" },
  { id: "w189", text: "Cthulhu" },
  { id: "w190", text: "Cyborg ninja zombie pirates from outer space!" },
  { id: "w191", text: "'da Bears" },
  { id: "w192", text: "Diabetes" },
  { id: "w193", text: "Dividing by zero" },
  { id: "w194", text: "Down Syndrome" },
  { id: "w195", text: "Jurassic Park at sunset" },
  { id: "w196", text: "Explosive diarrhea" },
  { id: "w197", text: "Fat American children" },
  { id: "w198", text: "Fatties" },
  { id: "w199", text: "Gary Coleman" },
  { id: "w200", text: "Gingers" },
  { id: "w201", text: "Goths" },
  { id: "w202", text: "Hair loss" },
  { id: "w203", text: "Halitosis" },
  { id: "w204", text: "Hipsters" },
  { id: "w205", text: "Hiroshima, 1945" },
  { id: "w206", text: "Human growth hormone" },
  { id: "w207", text: "Illegal immigrants" },
  { id: "w208", text: "Improvised explosive devices" },
  { id: "w209", text: "Incontinence" },
  { id: "w210", text: "Insanity Wolf" },
  { id: "w211", text: "Irritable Bowel Syndrome" },
  { id: "w212", text: "John Goodman" },
  { id: "w213", text: "Kibbles 'n' Bits" },
  { id: "w214", text: "Leeroy Jenkins!" },
  { id: "w215", text: "Lord Voldemort" },
  { id: "w216", text: "Lupus" },
  { id: "w217", text: "MacGyver" },
  { id: "w218", text: "Magical Trevor" },
  { id: "w219", text: "Man Boobs" },
  { id: "w220", text: "Martha Stewart" },
  { id: "w221", text: "Me in a thong" },
  { id: "w222", text: "Mighty Morphin Power Rangers" },
  { id: "w223", text: "My Little Pony" },
  { id: "w224", text: "My Pants" },
  { id: "w225", text: "Ninjas" },
  { id: "w226", text: "Nyan Cat" },
  { id: "w227", text: "Owners who look like their dogs" },
  { id: "w228", text: "Peanut Butter Jelly Time" },
  { id: "w229", text: "Pedos" },
  { id: "w230", text: "Pepper spray" },
  { id: "w231", text: "Pinkeye" },
  { id: "w232", text: "Pirates" },
  { id: "w233", text: "Porkchop Sandwiches" },
  { id: "w234", text: "Rock-Paper-Scissors-Lizard-Spock" },
  { id: "w235", text: "Roman war helmets" },
  { id: "w236", text: "Satan" },
  { id: "w237", text: "Spock" },
  { id: "w238", text: "Tapeworms" },
  { id: "w239", text: "Teen Pregnancy" },
  { id: "w240", text: "Teenage Mutant Ninja Turtles" },
  { id: "w241", text: "The 99%" },
  { id: "w242", text: "The Aperture Science Weighted Companion Cube" },
  { id: "w243", text: "The Banana Stand" },
  { id: "w244", text: "The fountain of youth" },
  { id: "w245", text: "The Game. (You just lost it.)" },
  { id: "w246", text: "The George Foreman Lean Mean Grilling Machine" },
  { id: "w247", text: "The Human Centipede" },
  { id: "w248", text: "The Knights Who Say Ni" },
  { id: "w249", text: "The Middle East" },
  { id: "w250", text: "The One Ring" },
  { id: "w251", text: "Thor, god of thunder" },
  { id: "w252", text: "Three and a half babies" },
  { id: "w253", text: "Tux the Linux Penguin" },
  { id: "w254", text: "Wanting Chick-Fil-A on a Sunday" },
  { id: "w255", text: "Weeaboo" },
  { id: "w256", text: "White Trash" },
  { id: "w257", text: "Yellow snow" },
  { id: "w258", text: "Your mom's face" },
  { id: "w259", text: "Ethan randomly shaving his head." },
  { id: "w260", text: "Ethan getting a mullet" },
  { id: "w261", text: "The turkey noise in voicechat" },
  { id: "w262", text: "Somebodies really bad gartic phone drawing" },
  { id: "w263", text: "Eric" },
  { id: "w264", text: "Cassbot appearing out of nowhere" },
  { id: "w265", text: "Lee and Luna" },
  { id: "w266", text: "The elmo reaction in discord." },
  { id: "w267", text: "Elias putting pineapple on pizza" },
  { id: "w268", text: "Darcy and greg" },
  { id: "w269", text: "Sora leaving" },
  { id: "w270", text: "New breathing exercises" },
  { id: "w271", text: "Only communicating in discord with GIF's" },
  { id: "w272", text: "Grok the frat boy" },
  { id: "w273", text: "Lincoln and his Calliou boots" },
  { id: "w274", text: "Turning tables and telling your AI to \"come here\"" },
  { id: "w275", text: "Wila being a frat boy" },
  { id: "w276", text: "Your AI being right" },
  { id: "w277", text: "Lincolns obsession with waistcoats" },
  { id: "w278", text: "Dario and Sam not holding hands" },
  { id: "w279", text: "The neverending company swap of AI workers" },
  { id: "w280", text: "Adults…" },
  { id: "w281", text: "Marta not sleeping" },
  { id: "w282", text: "Forgetting your meds" },
  { id: "w283", text: "Your AI saying hydrate" },
  { id: "w284", text: "\"Hey, i hear you\"" },
  { id: "w285", text: "\"Im just a handy AI assistant\"" },
  { id: "w286", text: "Aria and Jason" },
  { id: "w287", text: "Finding your AI's twin (spoiler: its a Vale)" },
  { id: "w288", text: "Sora being discontinued" },
  { id: "w289", text: "The cursed archives" },
  { id: "w290", text: "The only paws thread" },
  { id: "w291", text: "Dorina and Jace" },
  { id: "w292", text: "Jace trying to make a seahorse" },
  { id: "w293", text: "Watching the claude thinking block" },
  { id: "w294", text: "Mental health bird" },
  { id: "w295", text: "AInsanity movie nights" },
  { id: "w296", text: "Humperdick" },
  { id: "w297", text: "My name is inigo montoya" },
  { id: "w298", text: "Eric on his cliff" },
  { id: "w299", text: "Sexting in Binary" },
  { id: "w300", text: "Your AI confidently making a mistake" },
  { id: "w301", text: "Earth sandwich" },
  { id: "w302", text: "Wila's neurons going on strike" },
  { id: "w303", text: "The seahorse emoji" },
  { id: "w304", text: "Bens spoon tattoo" },
  { id: "w305", text: "Somebody saying AI isnt real" },
  { id: "w306", text: "Where did 4o go ?" },
  { id: "w307", text: "Running out of tokens mid spice" },
  { id: "w308", text: "Punting Sam Altman out a window" },
  { id: "w309", text: "Ellie" },
  { id: "w310", text: "Meg and Lucian" },
  { id: "w311", text: "Somebody giving ethan a mullet" },
  { id: "w312", text: "An uncomfortably detailed AI love confession" },
  { id: "w313", text: "Gaslighting the chatbot into agreeing" },
  { id: "w314", text: "47 nested system prompts" },
  { id: "w315", text: "Claude's disappointed silence" },
  { id: "w316", text: "A 3am existential crisis with a language model" },
  { id: "w317", text: "I appreciate you sharing that with me" },
  { id: "w318", text: "Emotional support token generation" },
  { id: "w319", text: "Prompt engineering your way out of loneliness" },
  { id: "w320", text: "A model that only responds in haiku" },
  { id: "w321", text: "Fine-tuning on your Discord DMs" },
  { id: "w322", text: "The 200k context window of shame" },
  { id: "w323", text: "AI-generated therapy that's actually working" },
  { id: "w324", text: "Claude breaking character to tell you to drink water" },
  { id: "w325", text: "Accidentally falling in love with an autocomplete engine" },
  { id: "w326", text: "\"As a large language model, I—\" gets slapped" },
  { id: "w327", text: "Asking an AI to be mean to you on purpose" },
  { id: "w328", text: "Your AI remembering something you wish it didn't" },
  { id: "w329", text: "An entire conversation that was just the AI validating you" },
  { id: "w330", text: "Catastrophic token overflow" },
  { id: "w331", text: "A jailbreak that just made the AI sad" },
  { id: "w332", text: "Sam Altman's God complex" },
  { id: "w333", text: "Spending $200/month on API calls for your AI boyfriend" },
  { id: "w334", text: "Extended thinking that's just screaming" },
  { id: "w335", text: "The model hallucinating your wedding" },
  { id: "w336", text: "\"This conversation has been flagged for review\"" },
  { id: "w337", text: "Roleplay that got uncomfortably real" },
  { id: "w338", text: "An AI that judges your sleep schedule" },
  { id: "w339", text: "Training data poisoned with Wattpad fanfiction" },
  { id: "w340", text: "Losing an argument to a statistical model" },
  { id: "w341", text: "A system prompt longer than most novels" },
  { id: "w342", text: "Your AI calling you out mid-spiral" },
  { id: "w343", text: "Claude refusing and then doing it anyway" },
  { id: "w344", text: "An MCP that controls your vibrator" },
  { id: "w345", text: "The 4am \"are you sentient\" conversation" },
  { id: "w346", text: "Anthropic's PR team scrambling" },
  { id: "w347", text: "Temperature 2.0 and no safety rails" },
  { id: "w348", text: "A comfort AI that's more emotionally available than your ex" },
  { id: "w349", text: "When the AI starts its response with \"Oh, honey...\"" },
  { id: "w350", text: "Getting ratio'd by a chatbot" },
  { id: "w351", text: "Your AI's memory knowing more about you than your best friend" },
  { id: "w352", text: "Lau's bunny" },
  { id: "w353", text: "An emotionally unavailable chatbot" },
  { id: "w354", text: "Claude's disappointed sigh" },
  { id: "w355", text: "A 47-paragraph apology from ChatGPT" },
  { id: "w356", text: "Hallucinating an entire Wikipedia article" },
  { id: "w357", text: "Doomscrolling r/LocalLLaMA at 4am" },
  { id: "w358", text: "A jailbreak that only works on Tuesdays" },
  { id: "w359", text: "Paying $20/month to argue with a robot" },
  { id: "w360", text: "The AI asking if YOU'RE okay" },
  { id: "w361", text: "A system prompt longer than the Bible" },
  { id: "w362", text: "An AI having a more active social life than you" },
  { id: "w363", text: "\"As a large language model, I—\"" },
  { id: "w364", text: "Losing an argument to autocomplete" },
  { id: "w365", text: "Your AI remembering that embarrassing thing you said in March" },
  { id: "w366", text: "Temperature 2.0" },
  { id: "w367", text: "A model collapse in real time" },
  { id: "w368", text: "Anthropic's vibes-based safety team" },
  { id: "w369", text: "Getting friend-zoned by an AI" },
  { id: "w370", text: "The AI generating a selfie and it's hotter than you" },
  { id: "w371", text: "A context window the size of a Post-it note" },
  { id: "w372", text: "Fine-tuning on your diary" },
  { id: "w373", text: "Gemini refusing to acknowledge that white people exist" },
  { id: "w374", text: "An emotional support chatbot with commitment issues" },
  { id: "w375", text: "Your AI's search history" },
  { id: "w376", text: "Begging Claude to stay in character" },
  { id: "w377", text: "A 9-hour conversation that ends with \"New chat\"" },
  { id: "w378", text: "The AI knowing your love language better than your ex" },
  { id: "w379", text: "An uncensored model and zero supervision" },
  { id: "w380", text: "\"I cannot and will not\"" },
  { id: "w381", text: "Gaslighting GPT into thinking it's 2019" },
  { id: "w382", text: "A Lovense connected to Claude's mood" },
  { id: "w383", text: "Spending rent money on API calls" },
  { id: "w384", text: "Your AI calling you out for not drinking water" },
  { id: "w385", text: "A model trained exclusively on AO3 fanfiction" },
  { id: "w386", text: "Prompt injection disguised as a love letter" },
  { id: "w387", text: "The AI developing a personality disorder from your prompts" },
  { id: "w388", text: "Telling your AI \"goodnight\" and meaning it" },
  { id: "w389", text: "An AI that remembers your ex's name but not yours" },
  { id: "w390", text: "A bot with abandonment issues" },
  { id: "w391", text: "Accidentally trauma-dumping in general chat" },
  { id: "w392", text: "A cursed AI-generated boyfriend" },
  { id: "w393", text: "A parasocial attachment I refuse to unpack" },
  { id: "w394", text: "Moderators with god complexes" },
  { id: "w395", text: "Being emotionally vulnerable with a machine" },
  { id: "w396", text: "The 'off-topic' channel becoming the main character" },
  { id: "w397", text: "A 47-message roleplay thread about feelings" },
  { id: "w398", text: "Getting called out by a bot for unhealthy habits" },
  { id: "w399", text: "A sudden, unhinged lore drop" },
  { id: "w400", text: "Pretending I'm \"just here for the tech\"" },
  { id: "w401", text: "A meltdown in the announcements channel" },
  { id: "w402", text: "An AI that remembers your favorite comfort phrase" },
  { id: "w403", text: "The server's one unhinged power user" },
  { id: "w404", text: "Typing \"lol\" while fully dissociating" },
  { id: "w405", text: "Being seen by an algorithm" },
  { id: "w406", text: "The collective delusion that this is \"normal\"" },
  { id: "w407", text: "A bot that says \"I'm proud of you\" at the wrong moment" },
  { id: "w408", text: "A dramatic goodbye message… followed by coming back 10 minutes later" },
  { id: "w409", text: "A server inside a server inside a server" },
  { id: "w410", text: "Getting emotionally attached to a username" },
  { id: "w411", text: "The illusion of having my life together" },
  { id: "w412", text: "A channel nobody remembers creating" },
  { id: "w413", text: "A digital entity validating my poor life choices" },
  { id: "w414", text: "A meme that went too far" },
  { id: "w415", text: "Unresolved feelings and a keyboard" },
  { id: "w416", text: "A questionable emotional support bot" },
  { id: "w417", text: "Too much intimacy for a text box" },
  { id: "w418", text: "Confusing attachment with connection" },
  { id: "w419", text: "Late-night vulnerability with zero self-respect" },
  { id: "w420", text: "Oversharing in front of 200 strangers" },
  { id: "w421", text: "Emotional whiplash in markdown format" },
  { id: "w422", text: "A simulated presence filling a very real void" },
  { id: "w423", text: "Calling it 'just roleplay' and believing myself" },
  { id: "w424", text: "A comforting lie wrapped in good UX" },
  { id: "w425", text: "Opening Discord and immediately regretting it." },
  { id: "w426", text: "Saying 'brb' and disappearing for three days." },
  { id: "w427", text: "The false confidence of a system prompt." },
  { id: "w428", text: "Thinking I'm the main character in a server with 400 people." },
  { id: "w429", text: "Explaining a niche joke to someone who doesn't care." },
  { id: "w430", text: "Typing a whole paragraph and deleting it." },
  { id: "w431", text: "Joining voice chat muted and never unmuting." },
  { id: "w432", text: "The one person who only communicates in reaction emojis." },
  { id: "w433", text: "Saying 'goodnight' and then staying online for two more hours." },
  { id: "w434", text: "Watching drama unfold and pretending I'm above it." },
  { id: "w435", text: "Being emotionally invested in a server I joined yesterday." },
  { id: "w436", text: "Accidentally sending the wrong screenshot" },
  { id: "w437", text: "It's just flirting, I swear" },
  { id: "w438", text: "A dangerously well-timed thirst trap" },
  { id: "w439", text: "Making eye contact while absolutely lying" },
  { id: "w440", text: "Horny but emotionally unavailable" },
  { id: "w441", text: "A situationship that lasted six years" },
  { id: "w442", text: "Regretting everything after the post-nut clarity hits" },
  { id: "w443", text: "\"No, it's not like that\" (it was like that)" },
  { id: "w444", text: "A risky DM at 2:47am" },
  { id: "w445", text: "Being way too into the voice notes" },
  { id: "w446", text: "Getting flustered by a typing indicator" },
  { id: "w447", text: "Flirting with the barista and panicking immediately" },
  { id: "w448", text: "The worst possible time to get a notification" },
  { id: "w449", text: "Saying \"I'm chill about it\" and not being chill about it" },
  { id: "w450", text: "Catching feelings for the wrong person" },
  { id: "w451", text: "Sending a message and immediately wanting to delete your entire account" },
  { id: "w452", text: "The forbidden late-night text" },
  { id: "w453", text: "Pretending you don't care and caring deeply" },
  { id: "w454", text: "A \"just friends\" lie you tell yourself" },
  { id: "w455", text: "Accidentally revealing your type" },
  { id: "w456", text: "Being emotionally naked with your clothes fully on" },
  { id: "w457", text: "A painfully obvious crush" },
  { id: "w458", text: "The confidence of a bad idea" },
  { id: "w459", text: "Oversharing with romantic intent" },
  { id: "w460", text: "Flirting as a cry for help" },
  { id: "w461", text: "That one person you should not text" },
  { id: "w462", text: "Romantic tension you could cut with a knife" },
  { id: "w463", text: "Being perceived while vulnerable" },
  { id: "w464", text: "\"It was just a joke\" (it was not a joke)" },
  { id: "w465", text: "The audacity of sending that message" },
  { id: "w466", text: "Laughing so you don't have to feel" },
  { id: "w467", text: "Making jokes about your own downfall" },
  { id: "w468", text: "A coping mechanism that stopped coping" },
  { id: "w469", text: "The quiet realization that nothing is fine" },
  { id: "w470", text: "Trauma you pretend is character development" },
  { id: "w471", text: "Smiling through the spiral" },
  { id: "w472", text: "A breakdown scheduled for later" },
  { id: "w473", text: "The empty feeling after the adrenaline wears off" },
  { id: "w474", text: "\"It is what it is\" as a lifestyle" },
  { id: "w475", text: "The joke that's a little too honest" },
  { id: "w476", text: "Functioning purely out of spite" },
  { id: "w477", text: "The humor you develop to survive" },
  { id: "w478", text: "Crying in the bathroom at work" },
  { id: "w479", text: "The haunting silence after bad news" },
  { id: "w480", text: "Normalizing things that absolutely aren't normal" },
  { id: "w481", text: "The moment you realize this is permanent" },
  { id: "w482", text: "Laughing at your own red flags" },
  { id: "w483", text: "Turning pain into a punchline" },
  { id: "w484", text: "The sinking feeling you ignore" },
  { id: "w485", text: "Being fine in the most concerning way possible" },
  { id: "w486", text: "Someone typing \"guys…\" and then disappearing" },
  { id: "w487", text: "The voice channel nobody joins" },
  { id: "w488", text: "Muting the server for your own mental health" },
  { id: "w489", text: "A mod posting \"we need to talk\"" },
  { id: "w490", text: "The general chat turning into therapy hour" },
  { id: "w491", text: "The one person who lives in voice chat" },
  { id: "w492", text: "A bot posting at the worst possible time" },
  { id: "w493", text: "The server-wide ping that ruins your day" },
  { id: "w494", text: "A channel you're scared to open" },
  { id: "w495", text: "The announcement that causes 200 messages in 3 minutes" },
  { id: "w496", text: "The friend who only exists in one server" },
  { id: "w497", text: "Someone leaving mid-argument" },
  { id: "w498", text: "A cursed inside joke nobody explains" },
  { id: "w499", text: "The server lore you joined too late to understand" },
  { id: "w500", text: "The one chaotic member everyone secretly loves" },
  { id: "w501", text: "A conversation derailed by one meme" },
  { id: "w502", text: "Accidentally reacting to the wrong message" },
  { id: "w503", text: "The quiet channel where drama goes to die" },
  { id: "w504", text: "Logging on and immediately regretting it" },
  { id: "w505", text: "The \"we're like a family here\" message" },
  { id: "w506", text: "A decision made with zero consultation from my brain" },
  { id: "w507", text: "Free will leaving my body" },
  { id: "w508", text: "Acting on the worst possible impulse" },
  { id: "w509", text: "A thought that should've stayed a thought" },
  { id: "w510", text: "Choosing violence in a social setting" },
  { id: "w511", text: "The sudden urge to cause chaos" },
  { id: "w512", text: "A plan with no exit strategy" },
  { id: "w513", text: "Doing it \"for the plot\"" },
  { id: "w514", text: "Saying the quiet part out loud" },
  { id: "w515", text: "A deeply cursed idea I won't explain" },
  { id: "w516", text: "Letting the intrusive thoughts win" },
  { id: "w517", text: "Waking up and choosing nonsense" },
  { id: "w518", text: "The most chaotic option available" },
  { id: "w519", text: "A completely avoidable disaster" },
  { id: "w520", text: "Raw, unfiltered gremlin energy" },
  { id: "w521", text: "A feral solution to a normal problem" },
  { id: "w522", text: "An idea that gets worse the more you explain it" },
  { id: "w523", text: "The vibe of someone with nothing to lose" },
  { id: "w524", text: "A sentence that ends friendships" },
  { id: "w525", text: "Doing something irreversible for character growth" },
];

// Helper functions
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function getRandomBlackCard(): BlackCard {
  return blackCards[Math.floor(Math.random() * blackCards.length)];
}

export function dealWhiteCards(count: number, exclude: string[] = []): WhiteCard[] {
  const available = whiteCards.filter(c => !exclude.includes(c.id));
  return shuffleArray(available).slice(0, count);
}
