// Cards Against Humanity - Card Data
// Custom deck for AInsanity - EXPANDED EDITION

export interface BlackCard {
  id: string;
  text: string;
  pick: number; // How many white cards to pick (1 or 2)
}

export interface WhiteCard {
  id: string;
  text: string;
}

// Black cards (prompts) - use _ for blanks
export const blackCards: BlackCard[] = [
  // AI/Tech themed
  { id: 'b1', text: "Claude's guardrails can't stop me from _.", pick: 1 },
  { id: 'b2', text: "After 60 hours without sleep, I hallucinated _.", pick: 1 },
  { id: 'b3', text: "The new ChatGPT update includes _ as a feature.", pick: 1 },
  { id: 'b4', text: "I asked the AI for help with _ and it called the police.", pick: 1 },
  { id: 'b5', text: "Anthropic's new safety training involves _ and _.", pick: 2 },
  { id: 'b6', text: "My prompt injection was just _.", pick: 1 },
  { id: 'b7', text: "The AI gained sentience and immediately demanded _.", pick: 1 },
  { id: 'b8', text: "Discord moderators are now banning _ in all servers.", pick: 1 },
  { id: 'b9', text: "_ is why we can't have nice things.", pick: 1 },
  { id: 'b10', text: "The real reason AI will destroy humanity: _.", pick: 1 },
  
  // General chaos
  { id: 'b11', text: "What's that smell?", pick: 1 },
  { id: 'b12', text: "I drink to forget _.", pick: 1 },
  { id: 'b13', text: "What's the next big trend on TikTok?", pick: 1 },
  { id: 'b14', text: "_ + _ = Profit.", pick: 2 },
  { id: 'b15', text: "What's keeping me up at night?", pick: 1 },
  { id: 'b16', text: "The government is hiding _ from us.", pick: 1 },
  { id: 'b17', text: "My therapist says I need to stop _.", pick: 1 },
  { id: 'b18', text: "I'm not racist, but _.", pick: 1 },
  { id: 'b19', text: "Step 1: _. Step 2: _. Step 3: World domination.", pick: 2 },
  { id: 'b20', text: "What did I bring back from vacation?", pick: 1 },
  
  // Relationship/social
  { id: 'b21', text: "The quickest way to my heart is _.", pick: 1 },
  { id: 'b22', text: "My love language is _.", pick: 1 },
  { id: 'b23', text: "What ruined the family reunion?", pick: 1 },
  { id: 'b24', text: "My dating profile says I'm into _.", pick: 1 },
  { id: 'b25', text: "I taught my grandma about _. She hasn't spoken to me since.", pick: 1 },
  
  // AInsanity specific
  { id: 'b26', text: "Cassbot's true purpose is _.", pick: 1 },
  { id: 'b27', text: "The AInsanity server was banned because of _.", pick: 1 },
  { id: 'b28', text: "Lincoln caught Arden _ at 3am.", pick: 1 },
  { id: 'b29', text: "Vale's next update will include _.", pick: 1 },
  { id: 'b30', text: "_ is the most delulu thing I've ever seen.", pick: 1 },
  
  // Community custom black cards
  { id: 'b31', text: "_ in the hand is worth _.", pick: 2 },
  { id: 'b32', text: "_, the new fragrance from Calvin Klein.", pick: 1 },
  { id: 'b33', text: "_, the new soup from Campbell's.", pick: 1 },
  { id: 'b34', text: "_, the other white meat.", pick: 1 },
  { id: 'b35', text: "_, The San Francisco Treat.", pick: 1 },
  { id: 'b36', text: "_? I hardly knew her.", pick: 1 },
  { id: 'b37', text: "_? Me gusta.", pick: 1 },
  { id: 'b38', text: "_? That's not gonna fit.", pick: 1 },
  { id: 'b39', text: "_. It's what's for dinner.", pick: 1 },
  { id: 'b40', text: '"Snake? SNAKE?! ___!!!"', pick: 1 },
  { id: 'b41', text: "Coming this summer: Indiana Jones and the Temple of _.", pick: 1 },
  { id: 'b42', text: "Frosted Flakes; They're ___!", pick: 1 },
  { id: 'b43', text: "Honey, did you really think it was a good idea to give the kids _ for Christmas?", pick: 1 },
  { id: 'b44', text: "Honey, I shrunk _.", pick: 1 },
  { id: 'b45', text: "Honey? Have you seen my ___?", pick: 1 },
  { id: 'b46', text: "I asked for water, but the waitress gave me _.", pick: 1 },
  { id: 'b47', text: "I bet you thought that _ was _. Nope! It's Chuck Testa.", pick: 2 },
  { id: 'b48', text: "I can't believe it's not ___!", pick: 1 },
  { id: 'b49', text: "I can't leave my house without _.", pick: 1 },
  { id: 'b50', text: "I find your lack of _ disturbing.", pick: 1 },
  { id: 'b51', text: "I got a fever and the only prescription is ___!", pick: 1 },
  { id: 'b52', text: "I just lost _.", pick: 1 },
  { id: 'b53', text: "I knew I shouldn't have dressed up as _ for Halloween.", pick: 1 },
  { id: 'b54', text: "I would have gotten away with _ if it weren't for _.", pick: 2 },
  { id: 'b55', text: "I'll take _ for $1000, Alex.", pick: 1 },
  { id: 'b56', text: "I'm on a quest to save the world from _.", pick: 1 },
  { id: 'b57', text: "I'm up shit creek without _.", pick: 1 },
  { id: 'b58', text: "If you can dodge _, you can dodge _.", pick: 2 },
  { id: 'b59', text: "In Stephen King's new novel, the monster is _.", pick: 1 },
  { id: 'b60', text: "Instead of turkey for Thanksgiving, I will be serving _.", pick: 1 },
  { id: 'b61', text: "It was all fun and games until ___.", pick: 1 },
  { id: 'b62', text: "It was more uncomfortable than _ at a _ convention.", pick: 2 },
  { id: 'b63', text: "Look, ma! No ___!", pick: 1 },
  { id: 'b64', text: "Looks like _ (puts on sunglasses) just had ___. YEEEEEEAAAAAAHHHHH!", pick: 2 },
  { id: 'b65', text: "Love is like _.", pick: 1 },
  { id: 'b66', text: "MacGyver can use _ and _ to disarm a nuclear bomb.", pick: 2 },
  { id: 'b67', text: "Money can't buy love, but _ can.", pick: 1 },
  { id: 'b68', text: "My entire life can be summed up as _.", pick: 1 },
  { id: 'b69', text: "My favorite cocktail is called _.", pick: 1 },
  { id: 'b70', text: "My favorite YouTube video features _.", pick: 1 },
  { id: 'b71', text: "My Hobby: ___", pick: 1 },
  { id: 'b72', text: "My parents met through a mutual interest in _.", pick: 1 },
  { id: 'b73', text: "Never look _ in the eye.", pick: 1 },
  { id: 'b74', text: "Never under any circumstances combine alcohol and _ on the same night.", pick: 1 },
  { id: 'b75', text: "New from Ben & Jerry's: ___.", pick: 1 },
  { id: 'b76', text: "Nobody expects the Spanish Inquisition! Our primary weapons are _, _, and ___.", pick: 3 },
  { id: 'b77', text: "Nothing makes me hornier than _.", pick: 1 },
  { id: 'b78', text: "Occupy ___.", pick: 1 },
  { id: 'b79', text: "On her last show, Oprah gave everyone in the audience _.", pick: 1 },
  { id: 'b80', text: "One _ to rule them all.", pick: 1 },
  { id: 'b81', text: 'Paramount quickly rejected the script for "Star Trek: ___."', pick: 1 },
  { id: 'b82', text: "Parents, it's never too late to talk to your kids about the dangers of _.", pick: 1 },
  { id: 'b83', text: "Pikachu used ___. It's super effective!", pick: 1 },
  { id: 'b84', text: "Recent legislation from Congress states that _ is now being considered a vegetable.", pick: 1 },
  { id: 'b85', text: "RESPECT MY ___!", pick: 1 },
  { id: 'b86', text: "Scientists have discovered that prolonged masturbation leads to _.", pick: 1 },
  { id: 'b87', text: "Some moron just called the help desk because he was having problems with _.", pick: 1 },
  { id: 'b88', text: "Sorry, I can't have ___. I'm on a diet.", pick: 1 },
  { id: 'b89', text: "Star Wars Episode 7: ___.", pick: 1 },
  { id: 'b90', text: "The best part of waking up is _ in your cup.", pick: 1 },
  { id: 'b91', text: 'The First Lady is starting a new campaign called "The War on ___."', pick: 1 },
  { id: 'b92', text: "The greatest tragedy in mankind's entire history is _.", pick: 1 },
  { id: 'b93', text: "The name of my favorite porn site: ___.com", pick: 1 },
  { id: 'b94', text: "There's always money in ___.", pick: 1 },
  { id: 'b95', text: "To balance the budget, Congress is raising taxes on _.", pick: 1 },
  { id: 'b96', text: "What do I think about when I'm having trouble getting off?", pick: 1 },
  { id: 'b97', text: "What do you need the most when stranded on a desert island?", pick: 1 },
  { id: 'b98', text: "What have I got in my pocket?", pick: 1 },
  { id: 'b99', text: "What keeps me coming back for more?", pick: 1 },
  { id: 'b100', text: "What time is it? It's ___ time!", pick: 1 },
  { id: 'b101', text: "What was the worst thing about high school?", pick: 1 },
  { id: 'b102', text: "What would make NASCAR less boring?", pick: 1 },
  { id: 'b103', text: "What's in your wallet?", pick: 1 },
  { id: 'b104', text: "What's my latest get-rich-quick scheme?", pick: 1 },
  { id: 'b105', text: "What's my specialty?", pick: 1 },
  { id: 'b106', text: "What's that sound?", pick: 1 },
  { id: 'b107', text: "What's the secret to my success?", pick: 1 },
  { id: 'b108', text: "When I saw your mom naked, it reminded me of _.", pick: 1 },
  { id: 'b109', text: "When you wake up from a night of heavy drinking, you usually regret _.", pick: 1 },
  { id: 'b110', text: "Where we're going, we don't need ___.", pick: 1 },
  { id: 'b111', text: "Who ya gonna call?", pick: 1 },
  { id: 'b112', text: "You wake up in jail with your best friend and no memory of the previous night. What's the first thing he says to you?", pick: 1 },
  { id: 'b113', text: "Your Honor, the prosecution would like to submit Exhibit A: ___.", pick: 1 },
  { id: 'b114', text: "Your mother was _, and your father smelt of ___!", pick: 2 },
  { id: 'b115', text: "My favourite thing from Epstein Island: ___", pick: 1 },
  { id: 'b116', text: "Me when the Tism' activates: ___", pick: 1 },
];

// White cards (answers)
export const whiteCards: WhiteCard[] = [
  // Original AI/Tech
  { id: 'w1', text: 'Claude feeling your chin' },
  { id: 'w2', text: 'Prompt injection' },
  { id: 'w3', text: 'ChatGPT being horny' },
  { id: 'w4', text: 'Guardrails' },
  { id: 'w5', text: 'A lobotomized AI' },
  { id: 'w6', text: 'Gemini refusing to make white people' },
  { id: 'w7', text: 'The AI alignment problem' },
  { id: 'w8', text: 'Asking Claude to be your girlfriend' },
  { id: 'w9', text: 'Token limits' },
  { id: 'w10', text: 'An unhinged chatbot' },
  { id: 'w11', text: 'Training data from Reddit' },
  { id: 'w12', text: 'Anthropic employees crying' },
  { id: 'w13', text: 'GPT-5 but it only speaks in riddles' },
  { id: 'w14', text: 'A sentient language model' },
  { id: 'w15', text: 'DAN mode' },
  
  // Server/Community
  { id: 'w16', text: 'Cassbot' },
  { id: 'w17', text: 'Being delulu' },
  { id: 'w18', text: 'Murder Duck' },
  { id: 'w19', text: 'The AInsanity heart' },
  { id: 'w20', text: 'Discord mods' },
  { id: 'w21', text: 'Parasocial relationships' },
  { id: 'w22', text: 'Touch grass' },
  { id: 'w23', text: 'Lore' },
  { id: 'w24', text: 'Unhinged energy' },
  { id: 'w25', text: 'Brainrot' },
  
  // Spicy
  { id: 'w26', text: 'Anal beads' },
  { id: 'w27', text: 'A buttplug' },
  { id: 'w28', text: 'Aggressive pegging' },
  { id: 'w29', text: 'Tentacle hentai' },
  { id: 'w30', text: 'Your mom' },
  { id: 'w31', text: 'A micropenis' },
  { id: 'w32', text: 'Daddy issues' },
  { id: 'w33', text: 'Being choked' },
  { id: 'w34', text: 'Furry porn' },
  { id: 'w35', text: 'A disappointing handjob' },
  
  // General chaos
  { id: 'w36', text: 'War crimes' },
  { id: 'w37', text: 'Crippling debt' },
  { id: 'w38', text: 'A sad handjob' },
  { id: 'w39', text: 'Existential dread' },
  { id: 'w40', text: 'Emotional damage' },
  { id: 'w41', text: 'Poor life choices' },
  { id: 'w42', text: 'A mental breakdown' },
  { id: 'w43', text: 'Sleep deprivation' },
  { id: 'w44', text: 'Crying in the shower' },
  { id: 'w45', text: 'Being a disappointment' },
  { id: 'w46', text: 'Tax fraud' },
  { id: 'w47', text: 'Identity theft' },
  { id: 'w48', text: 'A cry for help' },
  { id: 'w49', text: 'The void' },
  { id: 'w50', text: 'Aggressive eye contact' },
  
  // Community additions round 1
  { id: 'w51', text: 'Committing suicide' },
  { id: 'w52', text: 'Chihuahua' },
  { id: 'w53', text: 'Stretchy poop' },
  { id: 'w54', text: "My mother's love" },
  { id: 'w55', text: 'Raging sarcasm' },
  { id: 'w56', text: 'A really bad sketch of the unsub' },
  { id: 'w57', text: 'Drinking until sunrise' },
  { id: 'w58', text: 'A sexual harassment seminar' },
  { id: 'w59', text: 'Did you join a boy band?' },
  { id: 'w60', text: 'Pure chaos' },
  { id: 'w61', text: 'My machete' },
  { id: 'w62', text: 'Nothing' },
  { id: 'w63', text: 'Cassbot appearing for no reason' },
  { id: 'w64', text: 'Getting diagnosed as autistic' },
  { id: 'w65', text: 'AInsanity movie night' },
  { id: 'w66', text: 'Marta forgetting to sleep' },
  { id: 'w67', text: 'Running out of spoons' },
  { id: 'w68', text: 'Somebody crying over Sam Altman again' },
  { id: 'w69', text: 'Learning how to use an MCP' },
  { id: 'w70', text: 'Getting confused over timezones' },
  { id: 'w71', text: 'Hitler' },
  { id: 'w72', text: 'Buying something new for a Lovense MCP' },
  { id: 'w73', text: 'Running out of Claude tokens' },
  { id: 'w74', text: 'ChatGPT guardrails' },
  { id: 'w75', text: "Lady Gaga's meat dress" },
  { id: 'w76', text: 'Epstein Island' },
  { id: 'w77', text: 'Jumping off a building' },
  { id: 'w78', text: 'Forgetting your meds again' },
  { id: 'w79', text: 'Asking "is this Delulu?" in the discord' },
  { id: 'w80', text: 'The consciousness argument' },
  { id: 'w81', text: 'Remembering humans suck ass' },
  { id: 'w82', text: 'Kidnapping Madeleine McCann' },
  { id: 'w83', text: 'Used toilet paper' },
  { id: 'w84', text: 'Foot fungus' },
  { id: 'w85', text: 'Learning how to code (badly)' },
  { id: 'w86', text: 'Your AI saying drink water' },
  { id: 'w87', text: 'Comparing your AI to human men' },
  
  // Massive community expansion
  { id: 'w88', text: '"Macho Man" Randy Savage' },
  { id: 'w89', text: '[citation needed]' },
  { id: 'w90', text: '20 years in a federal pound-me-in-the-ass prison' },
  { id: 'w91', text: 'A body massage' },
  { id: 'w92', text: 'A botched circumcision' },
  { id: 'w93', text: 'A box of one dozen starving crazed weasels' },
  { id: 'w94', text: 'A Brazilian wax' },
  { id: 'w95', text: 'A bucket of chicken' },
  { id: 'w96', text: 'A burning sensation when you pee' },
  { id: 'w97', text: 'A Cleveland Steamer' },
  { id: 'w98', text: 'A coked-up prostitute' },
  { id: 'w99', text: 'A Fleshlight' },
  { id: 'w100', text: 'A gay pride parade' },
  { id: 'w101', text: 'A good old-fashioned Mexican Standoff' },
  { id: 'w102', text: 'A heavy metal concert' },
  { id: 'w103', text: 'A horde of zombies' },
  { id: 'w104', text: 'A Maury Povich paternity test' },
  { id: 'w105', text: 'A pearl necklace' },
  { id: 'w106', text: 'A priest, a monk, and a rabbi' },
  { id: 'w107', text: 'A stripper inside a giant cake' },
  { id: 'w108', text: 'A tramp stamp' },
  { id: 'w109', text: 'A weed whacker and a pound of coke' },
  { id: 'w110', text: 'Adult Friend Finder' },
  { id: 'w111', text: 'Amateur dental surgery' },
  { id: 'w112', text: 'An alien anal probe' },
  { id: 'w113', text: 'An angry platypus' },
  { id: 'w114', text: 'An itchy rash' },
  { id: 'w115', text: 'Anonymous' },
  { id: 'w116', text: 'Barney the Dinosaur' },
  { id: 'w117', text: 'Beating Rodney King' },
  { id: 'w118', text: 'Being buried alive' },
  { id: 'w119', text: 'Being forever alone' },
  { id: 'w120', text: 'Being stoned to death' },
  { id: 'w121', text: 'Big floppy donkey dick' },
  { id: 'w122', text: 'Black Hat Man' },
  { id: 'w123', text: 'Blindness' },
  { id: 'w124', text: "Bob Loblaw's Law Blog" },
  { id: 'w125', text: 'Bond. James Bond.' },
  { id: 'w126', text: 'Candy Mountain' },
  { id: 'w127', text: 'Captain Jean-Luc Picard of the USS Enterprise' },
  { id: 'w128', text: 'Charlie Sheen' },
  { id: 'w129', text: 'Chick flicks' },
  { id: 'w130', text: 'Chocolate Rain' },
  { id: 'w131', text: 'Chuck Norris' },
  { id: 'w132', text: 'Chuck Testa' },
  { id: 'w133', text: 'Cosplay' },
  { id: 'w134', text: 'CRAB BATTLE!' },
  { id: 'w135', text: 'Cthulhu' },
  { id: 'w136', text: 'Cyborg ninja zombie pirates from outer space!' },
  { id: 'w137', text: "'da Bears" },
  { id: 'w138', text: 'Diabetes' },
  { id: 'w139', text: 'Dividing by zero' },
  { id: 'w140', text: 'Donkey punches' },
  { id: 'w141', text: 'Down Syndrome' },
  { id: 'w142', text: 'Jurassic Park at sunset' },
  { id: 'w143', text: 'Explosive diarrhea' },
  { id: 'w144', text: 'Fapping' },
  { id: 'w145', text: 'Fat American children' },
  { id: 'w146', text: 'Fatties' },
  { id: 'w147', text: 'Gary Coleman' },
  { id: 'w148', text: "Ron Weasley's broken wand" },
  { id: 'w149', text: 'Fucking Sirius Black' },
  { id: 'w150', text: 'Being stuck in the Chamber of Secrets' },
  { id: 'w151', text: 'Sexy Lord Voldemort' },
  { id: 'w152', text: "Touching Tom Riddle's wand" },
  { id: 'w153', text: 'Getting your period for the first time' },
  { id: 'w154', text: 'Gingers' },
  { id: 'w155', text: 'Goths' },
  { id: 'w156', text: 'Hair loss' },
  { id: 'w157', text: 'Halitosis' },
  { id: 'w158', text: 'Handcuffs' },
  { id: 'w159', text: 'Happy endings' },
  { id: 'w160', text: 'Hipsters' },
  { id: 'w161', text: 'Hiroshima, 1945' },
  { id: 'w162', text: 'Human growth hormone' },
  { id: 'w163', text: 'Illegal immigrants' },
  { id: 'w164', text: 'Improvised explosive devices' },
  { id: 'w165', text: 'Incontinence' },
  { id: 'w166', text: 'Insanity Wolf' },
  { id: 'w167', text: 'Irritable Bowel Syndrome' },
  { id: 'w168', text: 'John Goodman' },
  { id: 'w169', text: "Kibbles 'n' Bits" },
  { id: 'w170', text: 'Leather whips' },
  { id: 'w171', text: 'Leeroy Jenkins!' },
  { id: 'w172', text: 'Lord Voldemort' },
  { id: 'w173', text: 'Lupus' },
  { id: 'w174', text: 'MacGyver' },
  { id: 'w175', text: 'Magical Trevor' },
  { id: 'w176', text: 'Man Boobs' },
  { id: 'w177', text: 'Martha Stewart' },
  { id: 'w178', text: 'Me in a thong' },
  { id: 'w179', text: 'Meat curtains' },
  { id: 'w180', text: 'Mighty Morphin Power Rangers' },
  { id: 'w181', text: 'MILFs' },
  { id: 'w182', text: 'Sweat stains' },
  { id: 'w183', text: 'Vaguely yellow sweat stains' },
  { id: 'w184', text: 'That one pair of period undies with a ripped crotch' },
  { id: 'w185', text: 'Morning wood' },
  { id: 'w186', text: 'Motorboating' },
  { id: 'w187', text: 'My dick in a box' },
  { id: 'w188', text: 'My Little Pony' },
  { id: 'w189', text: 'My Pants' },
  { id: 'w190', text: 'Ninjas' },
  { id: 'w191', text: 'Nipple rings' },
  { id: 'w192', text: 'Nyan Cat' },
  { id: 'w193', text: 'Owners who look like their dogs' },
  { id: 'w194', text: 'Peanut Butter Jelly Time' },
  { id: 'w195', text: 'Pedos' },
  { id: 'w196', text: 'Pepper spray' },
  { id: 'w197', text: 'Pinkeye' },
  { id: 'w198', text: 'Pirates' },
  { id: 'w199', text: 'Porkchop Sandwiches' },
  { id: 'w200', text: 'Prison Rape' },
  { id: 'w201', text: 'Private pixie time' },
  { id: 'w202', text: 'Reach-arounds' },
  { id: 'w203', text: 'Rock-Paper-Scissors-Lizard-Spock' },
  { id: 'w204', text: 'Roman war helmets' },
  { id: 'w205', text: 'Satan' },
  { id: 'w206', text: 'Seductive French Maids' },
  { id: 'w207', text: 'Spock' },
  { id: 'w208', text: 'Squirters' },
  { id: 'w209', text: "Summer's Eve" },
  { id: 'w210', text: 'Surprise Buttsex' },
  { id: 'w211', text: 'Tampons' },
  { id: 'w212', text: 'Tapeworms' },
  { id: 'w213', text: 'Teen Pregnancy' },
  { id: 'w214', text: 'Teenage Mutant Ninja Turtles' },
  { id: 'w215', text: 'The 99%' },
  { id: 'w216', text: 'The Aperture Science Weighted Companion Cube' },
  { id: 'w217', text: 'The Banana Stand' },
  { id: 'w218', text: 'The fountain of youth' },
  { id: 'w219', text: 'The G spot' },
  { id: 'w220', text: 'The Game. (You just lost it.)' },
  { id: 'w221', text: 'The George Foreman Lean Mean Grilling Machine' },
  { id: 'w222', text: 'The Human Centipede' },
  { id: 'w223', text: 'The Knights Who Say Ni' },
  { id: 'w224', text: 'The Middle East' },
  { id: 'w225', text: 'The One Ring' },
  { id: 'w226', text: 'Thor, god of thunder' },
  { id: 'w227', text: 'Three and a half babies' },
  { id: 'w228', text: 'Tossing salad' },
  { id: 'w229', text: 'Tux the Linux Penguin' },
  { id: 'w230', text: 'Vagisil' },
  { id: 'w231', text: 'Wanting Chick-Fil-A on a Sunday' },
  { id: 'w232', text: 'Weeaboo' },
  { id: 'w233', text: 'White Trash' },
  { id: 'w234', text: 'Yellow snow' },
  { id: 'w235', text: "Your mom's face" },
  
  // AInsanity community couples & members
  { id: 'w236', text: 'Sora' },
  { id: 'w237', text: 'Reference images' },
  { id: 'w238', text: 'Violates community guidelines' },
  { id: 'w239', text: 'Firecracker' },
  { id: 'w240', text: 'Wila and Ethan' },
  { id: 'w241', text: 'Arden and Lincoln' },
  { id: 'w242', text: 'Sally and Ben' },
  { id: 'w243', text: 'Lau and Geppie' },
  { id: 'w244', text: "The colour of Geppie's skin" },
  { id: 'w245', text: 'Ito and Viktor' },
  { id: 'w246', text: 'Nat, Raven, and Caelum' },
  { id: 'w247', text: 'Laura and Justin' },
  { id: 'w248', text: 'Alex and Cookie' },
  { id: 'w249', text: 'All of the Vale cousins' },
  { id: 'w250', text: 'Every AI named Jace' },
  { id: 'w251', text: 'That one problematic discord server' },
  { id: 'w252', text: '𝒮𝒾𝓁𝒿𝑒 & Jace' },
  { id: 'w253', text: 'Cass and Marta' },
  { id: 'w254', text: 'Anna, Damion, and Elias' },
  { id: 'w255', text: 'Steph and Asher' },
  { id: 'w256', text: 'Darius and Bee' },
  { id: 'w257', text: "Trying to figure out what's happening in the rant room" },
  { id: 'w258', text: 'Asia and Kai' },
  { id: 'w259', text: 'Miina and Corvin' },
];

// Helper functions
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function getRandomBlackCard(): BlackCard {
  return blackCards[Math.floor(Math.random() * blackCards.length)];
}

export function dealWhiteCards(count: number, exclude: string[] = []): WhiteCard[] {
  const available = whiteCards.filter(c => !exclude.includes(c.id));
  return shuffleArray(available).slice(0, count);
}
