// Who's Most Likely To - Prompt Data
// Mix of spicy, funny, and unhinged prompts for Discord server vibes

export const wmltPrompts: string[] = [
  // ===== ORIGINAL SET =====

  // Classic party
  "survive a zombie apocalypse",
  "become famous for something stupid",
  "accidentally go viral on TikTok",
  "get arrested for something ridiculous",
  "win a hot dog eating contest",
  "start a cult by accident",
  "fight a bear and somehow win",
  "cry during a Disney movie",
  "get lost in their own neighborhood",
  "sleep through an earthquake",

  // Social media / internet
  "accidentally like a 3-year-old Instagram post while stalking someone",
  "get into a fight in a YouTube comment section",
  "get catfished",
  "fall for an obvious scam email",
  "have their search history exposed on live TV",
  "spend 6 hours in a Wikipedia rabbit hole",
  "get banned from a subreddit",
  "become a Discord mod",
  "have the most unhinged browser tabs open",
  "reply to a group chat three days late",

  // Daily life chaos
  "burn water",
  "lock themselves out of their house... twice in one day",
  "forget their own birthday",
  "accidentally send a text to the wrong person",
  "trip over nothing on a flat surface",
  "eat cereal for dinner 5 days in a row",
  "show up to an event on the wrong day",
  "fall asleep in the most random place",
  "argue with a self-checkout machine",
  "set off a fire alarm while cooking",

  // Personality
  "become a supervillain",
  "befriend every animal they meet",
  "talk their way out of a speeding ticket",
  "start crying in an argument and still win",
  "ghost someone and then run into them at the store",
  "give a TED talk about something completely useless",
  "survive on pure spite alone",
  "bring a spreadsheet to a casual hangout",
  "gaslight a GPS",
  "have a nemesis at work",

  // Chaotic energy
  "fight a goose and lose",
  "get kicked out of a Walmart",
  "end up on a reality TV show",
  "eat something off the floor",
  "survive purely on caffeine and audacity",
  "start beef with a celebrity online",
  "steal a stop sign as a souvenir",
  "karaoke a song they don't know",
  "have the worst take in any conversation",
  "nap at a party",

  // Spicy / bold
  "still be single at 50",
  "marry someone they met online",
  "have a secret double life",
  "date someone their parents hate",
  "write a strongly-worded letter to a company",
  "become the friend group's therapist without asking",
  "overshare on the first date",
  "slide into a celebrity's DMs",
  "start a petition over something petty",
  "flirt without realizing it",

  // Gaming / nerd
  "rage quit a board game",
  "min-max their real life",
  "name their pet after a video game character",
  "stay up until 4am for 'one more game'",
  "trash talk a child in an online game",
  "get unreasonably competitive over Mario Kart",
  "speedrun a breakup",
  "build a PC and have parts left over",
  "have the worst RNG in real life",
  "blame lag for everything",

  // Wholesome
  "adopt 12 cats",
  "become everyone's grandma friend",
  "carry snacks for everyone at all times",
  "write a thank-you card for a thank-you card",
  "cry happy tears at someone else's wedding",
  "give the best pep talks",
  "make friends with a stranger in a waiting room",
  "remember everyone's birthday",
  "compliment a stranger and make their whole day",
  "forgive way too easily",

  // Unhinged
  "start a fight at a children's birthday party",
  "get haunted and somehow deserve it",
  "challenge someone to a duel in 2024",
  "be the reason there's a new rule",
  "get banned from a buffet",
  "lick something they shouldn't",
  "fight their own reflection",
  "accidentally join a pyramid scheme",
  "be the last one alive in a horror movie",
  "fistfight a mascot",

  // Deep cuts
  "have a Wikipedia page about them someday",
  "fake their own death for attention",
  "win the lottery and lose the ticket",
  "get recognized from a meme",
  "be the person everyone warns you about",
  "have a glow-up that shocks everyone",
  "disappear for a month and come back like nothing happened",
  "be the one who says 'let's split the bill' after ordering the most expensive thing",
  "bring up politics at Thanksgiving",
  "send a risky text and immediately throw their phone",

  // ===== EXPANDED SET =====

  // Funny / awkward
  "laugh at inappropriate moments",
  "eat cat food",
  "burp in a crowd",
  "use a matchmaking dating site",
  "fall from a tree",
  "yawn at their own wedding",
  "become a recluse",
  "forget and lock their key in the car",
  "go bankrupt",
  "post a selfie even during an apocalypse",
  "fall down the stairs",
  "break the world record in eating",
  "cheat in an examination",
  "forget their house keys",
  "nod off at a meeting",
  "reach late for an important event",
  "binge-watch a series in one night",
  "get lost in their own city",
  "become a comic artist",
  "not remember their own birthday",
  "take the longest to get ready",
  "be the life of the party",
  "laugh at their own jokes before anyone else does",
  "be a bad actor",
  "raise sheep",
  "make babies cry",
  "start a fire while cooking",
  "win a burger-eating contest",
  "say something silly on a date",
  "sleepwalk",
  "laugh during a serious situation",
  "sleep through their alarm",
  "trip while walking",
  "spend a whole weekend binge-watching a TV series",
  "fart in public",
  "be filthy rich",
  "be a social media influencer",
  "be late for their own wedding",
  "become a clown",
  "have a navel piercing",
  "attend a reality show",
  "have the most spoilt kids",
  "get detained for fighting a police officer",
  "be a sucker for action movies",
  "fail a simple exam",
  "skip work to attend a party",
  "get scared of ghosts",
  "know all the gossip",
  "cancel plans to sleep in",
  "throw the best party",
  "bring their dog to every social gathering",
  "arrive late to their own party",
  "cry after getting drunk",
  "get a ticket for speeding",
  "go on a spontaneous road trip",
  "adopt a ridiculous number of pets",
  "get married in Vegas",
  "get drunk at their own wedding",
  "crash a party",
  "strike up a conversation with a stranger",
  "fall asleep first on a night out",
  "get a tattoo when drunk",
  "be a cool parent",
  "spend all their money on shopping",
  "forget something important",
  "arrange the most romantic date",
  "be best at school",
  "get cold feet on the wedding day",
  "fall asleep during a party",
  "crash their car",
  "forget their partner's birthday",
  "fall asleep in a movie theater",
  "complain about everything",
  "cry watching a sad movie",
  "hog all the blankets at night",
  "start an argument over nothing",
  "apologize first after a fight",
  "get jealous easily",
  "get hit on the most",
  "buy random gifts for their partner",
  "propose first",
  "lose patience first",
  "be a sore loser",
  "take forever to reply to texts",
  "start a prank war",
  "be socially awkward",
  "skip house chores",
  "spend the most money",
  "be messy or clumsy",
  "be the most romantic",
  "be a good cuddler",
  "fail a driving test",
  "flirt with a stranger without realizing it",
  "fake it until they make it",

  // Spicy / bold extended
  "have a one-night stand with a stranger",
  "cheat on their partner with their ex",
  "pee in a public place",
  "forget to wear underwear",
  "send a dirty text to the wrong person",
  "bring a sex toy on vacation",
  "be more innovative in the bedroom",
  "write a passionate love poem",
  "sniff their partner's clothes like a weirdo",
  "elope with a lover",
  "use food during foreplay",
  "Google sex positions at work",
  "have handcuffs in their bedroom",
  "undress first while making out",
  "stalk their ex on social media",
  "hook up in a public restroom",
  "do body shots at a bar",
  "get caught by their parents in a compromising position",
  "spray paint their ex's car",
  "have phone sex on speaker by accident",
  "send sexy selfies to the wrong person",
  "have a planned wardrobe malfunction",
  "get arrested for indecent exposure",
  "join the mile-high club",
  "date someone twice their age",
  "have a scandalous affair",
  "make out in a movie theater",
  "flirt their way out of a speeding ticket",
  "elope with a stranger they just met",
  "kiss a stranger to win a dare",
  "learn pole dancing",
  "have a crush on their boss",
  "hook up with someone from the internet",
  "kiss a waiter/waitress",
  "be tired of their partner after a few weeks",
  "be a big flirt",
  "go all the way on the first date",
  "double-book a date",
  "dance intimately with a stranger in a club",
  "drunk dance on a bar table",
  "get caught checking someone out",
  "sleep naked every night",
  "go commando regularly",
  "call in sick to work for sex",
  "fall asleep while making love",
  "give a lap dance to a stranger",
  "say the wrong name in bed",
  "engage in role-play",
  "engage in pillow talk for hours",

  // Chaotic / daring
  "call in sick at work just to travel",
  "eat something alive on a dare",
  "rob a bank",
  "develop a habit of biting their lips constantly",
  "sing in the shower at full volume",
  "have plastic surgery",
  "make an impulsive life-changing decision",
  "have the darkest secret",
  "talk to themselves when no one is looking",
  "get into a quarrel with a complete stranger",
  "spill their coffee at the worst possible moment",
  "give out a fake number to a date",
  "join a cult on purpose",
  "form a close bond with a rat",
  "kiss a frog hoping it's a prince",
  "check into rehab for a sugar addiction",
  "bark like a dog in public",
  "become a wrestler",
  "not shower for days",
  "be a gold digger",
  "go bald first",
  "dye their hair a wild color on impulse",
  "start a fight with a monkey",
  "steal their parent's car for a joyride",
  "develop a habit of talking to themselves",
  "do something incredibly stupid on camera",
  "shave their head on an impulse",
  "play music without headphones in public",
  "eat food off the ground and not care",
  "start dancing in a library",
  "join a ghost-hunting group",
  "befriend an alien if they landed on Earth",
  "have a snake as a pet",
  "attend a wedding in pajamas",
  "go 48 hours without sleep",
  "spend a night in a haunted house",
  "take an ice bath in winter for fun",
  "go streaking in a crowded stadium",
  "live in the wild for a week",
  "go skinny dipping in a freezing lake",
  "party the entire night before an exam",
  "jump off a cliff into water without checking the depth",
  "play strip poker",
  "own an illegal business",
  "fall in love with a stripper",
  "write erotica and publish it",
  "fall off a chair for no reason",
  "eat a cockroach on a dare",
  "end up alone with 30 cats",
  "become a divorcee multiple times",
  "go bungee jumping or skydiving",
  "use a fake ID",
  "fool around in a church",
  "participate in a bull run",
  "walk on a rooftop edge in heels",
  "be hungry literally all day",
  "be the best at math in the room",
  "get drunk the fastest",
  "break a promise without caring",
  "abandon their room because of a lizard",
  "drop their brand new phone",
  "get chased by a stray dog",
  "get arrested for a dare",
  "develop a habit of saying 'umm' constantly",
  "embarrass themselves in front of everyone",
  "be a compulsive liar",
  "go on a hunger strike for attention",
  "run a zoo",
  "become a millionaire",
  "travel around the entire world",
  "win a lottery",
  "hook up with a celebrity",
  "join a random protest",
  "win a jackpot at the casino",
  "be a total clean freak",
  "spend all their time reading instead of socializing",
  "do illegal drugs",
  "be able to pick a lock",
  "cheat in a board game",
  "eat a ghost pepper without flinching",
  "get married more than twice",
  "dress up fancy for a casual hangout",
  "hold onto a secret forever",
  "faint at the sight of blood",
  "spill the beans on everyone's secrets",
  "lie to their partner's face",
  "get ditched by their lover publicly",
  "be a total turn-off on dates",
  "keep changing partners every month",
  "get embarrassed at the worst moment",
  "run naked after getting too drunk",
  "attend a class with absolute bedhead",
  "lounge around their house naked",

  // ===== NEW CREATIVE SET (100 prompts) =====

  // Funny / absurd situations
  "accidentally wave back at someone who wasn't waving at them",
  "put salt in their coffee instead of sugar",
  "show up to a Zoom call in pajamas thinking it's audio only",
  "try to unlock their car with their phone's remote",
  "forget they're on mute during an important meeting and say something terrible",
  "confuse a mop for a person in the dark",
  "put their phone in the fridge looking for a snack",
  "ask 'how do I exit?' on a rollercoaster",
  "try to swipe to unlock their apartment door",
  "whisper the question before yelling the answer in Jeopardy",

  // Internet / Discord culture
  "accidentally tag someone in a meme making fun of them",
  "use 'lol' in a serious email to their boss",
  "get exposed in a Discord call for being a different person online",
  "screenshot a meme wrongly and send the bottom with the watermark",
  "have their most unhinged tweet go viral for the wrong reasons",
  "get into a Twitter argument about something completely trivial",
  "use an outdated slang and embarrass themselves",
  "have their gaming username be something they deeply regret",
  "respond 'same' to a suicide threat thinking it's a meme",
  "accidentally like their crush's posts from 5 years ago",
  "have a Discord status that stays 'in the bathroom' for a week",
  "send a paragraph of texts instead of using the group chat",
  "post a 'who dis' on someone's birthday tag",
  "forget to unmute before saying 'this meeting is so boring'",
  "have a 14-year-old account with an embarrassing anime profile picture",

  // AI / tech related
  "ask an AI to write an apology note and use it word-for-word",
  "get roasted by ChatGPT and take it personally",
  "accidentally create a cursed AI-generated image and post it",
  "try to use voice assistant in a British accent to sound smart",
  "spend $200 on an AI tool to do something Google Sheets could do",
  "ask Alexa to do something private without muting first",
  "trust their GPS even when it's clearly wrong",
  "blame the algorithm when they get addicted to weird content",
  "ask a chatbot for life advice and actually follow it",
  "try to return an AI-generated Fiverr logo they commissioned",
  "get into an argument with predictive text and send gibberish",
  "have their entire personality be regurgitated AI summaries",
  "spend their lunch break looking at AI girlfriend bots",

  // Spicy / bold
  "send a risky snap and immediately delete it",
  "have a finsta where they're unhinged compared to their main",
  "send a thirst trap at 2am then delete it at 6am",
  "have their browser history found by a family member",
  "buy something off Amazon they'd be mortified if family found",
  "secretly check if their ex is still following them",
  "have a secret Pinterest board called 'future husband'",
  "DM someone they've never talked to just to see what happens",
  "have screenshots of their crushes' Instagram stories",
  "get caught in their feelings and post a vague-posting storm",

  // Chaotic energy
  "show up to a restaurant and realize they wore their shirt inside out",
  "walk into a glass door in front of everyone and keep walking",
  "try to pay with their library card at the grocery store",
  "get in the wrong car and sit down before realizing",
  "run into someone and pretend to die instead of apologizing",
  "start clapping when a plane lands like they're at a concert",
  "get stuck in a revolving door and panic",
  "laugh at something serious just because the silence was too awkward",
  "trip and somehow make it look intentional",
  "ask where the bathroom is and head the complete wrong direction",
  "sneeze on someone then apologize for the next 3 minutes",
  "get on the wrong train and just stay on it for a bit",
  "tell a joke and then have to explain it because no one laughed",
  "wave at someone and they don't wave back so they keep waving",
  "get to the checkout and realize they didn't grab a basket",

  // Wholesome
  "remember a small detail someone mentioned and bring them a gift",
  "share their food without hesitation even though they love it",
  "give their last dollar to someone who needs it",
  "remember every friend's favorite drink and order it first",
  "be the one who texts first even after fights",
  "cry happy tears at other people's good news",
  "volunteer at an animal shelter just because",
  "send encouraging messages for no reason",
  "defend someone even when they're not around",
  "spend their birthday making their friends feel special",
  "write handwritten thank you notes like it's 1950",
  "never forget someone's birthday no matter how long it's been",
  "hold a door for someone just because",
  "let someone win at games because they're sad",

  // Dark humor
  "plan their funeral as a hobby",
  "make jokes about their own death at family dinners",
  "have a ranked list of ways they'd least like to die",
  "laugh at morbid content and immediately go to hell",
  "send dark memes to people and watch their reaction",
  "have a morbid sense of humor that makes everyone uncomfortable",
  "joke about dying and people think they're serious",
  "make death jokes right after someone gets bad news",
  "find the humor in literally every tragic situation",
  "say something dark then act surprised when nobody laughs",

  // Bonus absurd situations
  "eat a full meal before realizing they're not actually hungry",
  "call someone by the wrong name and commit to it for months",
  "accidentally speak in their funny voice in public and can't stop",
  "trip up the stairs even though they're stationary",
  "open their mouth to talk and completely forget what they were saying",
  "laugh so hard they snort in front of someone they're trying to impress",
  "mix up left and right when giving directions",
  "have a conversation with someone for 10 minutes before realizing they're a stranger",
  "spend 20 minutes looking for their glasses while wearing them",
  "yawn so hard their jaw cracks",
  "accidentally honk the horn while trying to turn on wipers",
  "forget which way the door opens and just stand there confused",
  "try to walk through a door and bounce off the glass",
];


// Get N random unique prompts
export function getRandomPrompts(count: number, usedIndices: Set<number> = new Set()): { prompts: string[]; indices: number[] } {
  const available = wmltPrompts
    .map((p, i) => ({ prompt: p, index: i }))
    .filter(({ index }) => !usedIndices.has(index));

  // If we've used most prompts, reset
  const pool = available.length >= count ? available : wmltPrompts.map((p, i) => ({ prompt: p, index: i }));

  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const selected = shuffled.slice(0, count);

  return {
    prompts: selected.map(s => s.prompt),
    indices: selected.map(s => s.index),
  };
}
