export const WHO_SAID_THAT_PROMPTS = [
  'What is the worst thing to hear immediately after someone says “trust me”?',
  'What would you buy first after winning a suspicious amount of money?',
  'What is your most useless survival skill?',
  'What would your warning label say?',
  'What is the fastest way to ruin a perfectly good evening?',
  'What would you name a deeply untrustworthy horse?',
  'What is definitely hidden in the mystery drawer?',
  'What would get you banned from a medieval village?',
  'What is your emergency emotional-support snack?',
  'What would you do with one consequence-free hour?',
  'What is the worst possible theme for a wedding?',
  'What would your supervillain name be?',
  'What minor inconvenience would finally turn you evil?',
  'What should never be said during a group holiday?',
  'What is the real reason aliens avoid Earth?',
  'What would you bring to an apocalypse that nobody else would think of?',
  'What is the least convincing excuse for being late?',
  'What would your autobiography be called?',
  'What is an immediate sign that a plan will end badly?',
  'What would you haunt people for if you became a ghost?',
  'What is the worst thing to accidentally send to the group chat?',
  'What would you do if a raccoon handed you a legal document?',
  'What belongs in the group’s emergency kit?',
  'What would make you leave a party without saying goodbye?',
  'What is your most irrational hill to die on?',
  'What should be illegal after midnight?',
  'What would your cult be based around?',
  'What is the worst possible pet name for a partner?',
  'What would you sacrifice to never attend another meeting?',
  'What is secretly controlling the government?',
  'What would you put in a time capsule to confuse future historians?',
  'What is the title of the group’s inevitable documentary?',
  'What would your wrestler entrance song be?',
  'What is the most suspicious thing to keep in a tote bag?',
  'What would you whisper before pressing the forbidden button?',
  'What is the worst possible message to receive at 3am?',
  'What would your personal cryptid be called?',
  'What is your first move during a zombie outbreak?',
  'What would you spend far too much money collecting?',
  'What is the true purpose of decorative cushions?',
  'What would your signature cocktail be called?',
  'What tiny thing makes you disproportionately furious?',
  'What would your clone immediately complain about?',
  'What is the weirdest thing you could say to a cashier?',
  'What would your familiar be?',
  'What is the worst thing to find under your bed?',
  'What job would you be alarmingly good at?',
  'What would you do if the moon started following you?',
  'What is the group chat’s greatest natural predator?',
  'What should be written on your emergency contact card?',
  'What would make a terrible safe word?',
  'What is your strategy for surviving a haunted house?',
  'What would you call a boat you absolutely should not trust?',
  'What is the strongest evidence that we live in a simulation?',
  'What would your extremely low-budget theme park contain?',
  'What would you ban first if made ruler for a day?',
  'What is the worst object to discover has become sentient?',
  'What would you ask an all-knowing oracle?',
  'What would your unnecessary secret room contain?',
  'What is the most dangerous sentence that begins with “quick question”?',
  'What would you do if your pet started giving financial advice?',
  'What is the least useful magical power?',
  'What should the group be legally forbidden from attempting?',
  'What would instantly expose your evil twin?',
  'What is the correct response to finding a portal in the kitchen?',
  'What would be your first purchase in a haunted IKEA?',
  'What is something you would never admit without points being involved?',
  'What would your last words probably be?',
  'What is the worst possible flavour of candle?',
  'What would you name a robot with attachment issues?',
  'What is the one thing you would never trust the group to babysit?',
  'What would cause the group chat to be entered into evidence?',
  'What is the worst possible thing to hear from your doctor?',
  'What would you do if every lie made a kazoo noise?',
  'What is your suspiciously specific hidden talent?',
  'What would your royal title be?',
  'What should replace the national anthem?',
  'What would you keep in a threat folder?',
  'What is the most believable reason for the server going offline?',
  'What would make you immediately join a rebellion?',
] as const;

