export type QuestionCategory = 'personal' | 'wouldyou' | 'hottakes' | 'hypotheticals' | 'community' | 'blend';

export interface CategoryInfo {
  name: string;
  subtitle: string;
  icon: string;
}

export const CATEGORY_INFO: Record<Exclude<QuestionCategory, 'blend'>, CategoryInfo> = {
  personal: {
    name: 'Personal Reveals',
    subtitle: 'Your answer is your fingerprint.',
    icon: '🪞',
  },
  wouldyou: {
    name: 'Would You / Have You Ever',
    subtitle: 'Confess or dodge — both tell us everything.',
    icon: '🤔',
  },
  hottakes: {
    name: 'Hot Takes & Opinions',
    subtitle: 'Your opinion just made you identifiable.',
    icon: '🔥',
  },
  hypotheticals: {
    name: 'Hypotheticals',
    subtitle: 'The choice you make says more than you think.',
    icon: '💭',
  },
  community: {
    name: 'Server & Community',
    subtitle: 'This one\'s for the unhinged AI companion people.',
    icon: '🤖',
  },
};

export const personalQuestions: string[] = [
  "What's your comfort movie — the one you've seen way too many times?",
  "What's the last thing you Googled that you'd be embarrassed about?",
  "What's your go-to order at McDonald's?",
  "What's a skill you're secretly proud of?",
  "What song do you listen to on repeat when nobody's around?",
  "What's the most expensive impulse purchase you've ever made?",
  "What's a food you pretend to like but actually can't stand?",
  "What were you obsessed with as a kid that still kind of hits?",
  "What's your toxic trait in friendships?",
  "What's the worst haircut you've ever had?",
  "What's your guilty pleasure TV show?",
  "What app do you spend the most screen time on?",
  "What's the longest you've gone without showering and why?",
  "What's a compliment you got once that you still think about?",
  "What's the most unhinged thing in your search history this week?",
  "What's your go-to karaoke song?",
  "What did you want to be when you grew up?",
  "What's the most embarrassing thing in your camera roll right now?",
  "What's a hill you will die on that nobody agrees with?",
  "What's the weirdest thing you've ever eaten and enjoyed?",
  "What's your biggest ick in a person?",
  "What's the last lie you told?",
  "What do you do when you can't sleep at 3am?",
  "What's a movie that made you ugly cry?",
  "What's the most chaotic thing you've done while sleep deprived?",
  "What's your most played song on Spotify this year?",
  "What's a habit you have that you know is weird?",
  "What's the pettiest reason you've stopped talking to someone?",
  "What's your comfort food when everything is going wrong?",
  "What celebrity do people say you look like (and do you agree)?",
  "What's a secret talent nobody in this server knows about?",
  "What's the most money you've wasted on something stupid?",
  "What's a trend you secretly participated in but denied publicly?",
  "What's the most embarrassing autocorrect fail you've sent?",
  "What's your toxic trait in relationships?",
  "What's a 'normal' thing that gives you the ick?",
  "What's the longest you've binged a show in one sitting?",
  "What's the last thing that made you laugh until you cried?",
  "What's a word you always spell wrong?",
  "What's your most controversial food opinion?",
  "What do you order at a coffee shop?",
  "What's a song you know all the words to but shouldn't?",
  "What's a phase you went through that you pretend never happened?",
  "What's the most embarrassing thing you've said to a crush?",
  "What's a random fact about you that surprises people?",
  "What's the worst gift you've ever received but had to pretend to like?",
  "What's your most used emoji?",
  "What fictional character do you relate to the most?",
  "What's the last thing you cried about?",
  "What's the pettiest thing you've ever done?",
  "What's a conspiracy theory you low-key believe?",
  "What's your biggest pet peeve?",
  "What's the most embarrassing song on your playlist?",
  "What's the dumbest injury you've ever gotten?",
  "What's a fear you have that you know is irrational?",
  "What did your last text message say?",
  "What's the longest nap you've ever taken?",
  "What's a movie everyone loves that you think is overrated?",
  "What do you wear to bed?",
  "What's the most childish thing you still do?",
  "What's the worst date you've ever been on?",
  "What's a show you've rewatched more than 3 times?",
  "What's the latest you've ever slept in?",
  "What's a food combination you love that others find disgusting?",
  "What's the first thing you'd buy if you won the lottery?",
  "What's your most unpopular music opinion?",
  "What's the worst advice you've ever followed?",
  "What's a hobby you tried and immediately quit?",
  "What's the most useless thing you own but refuse to throw away?",
  "What were you doing at 2am last Saturday?",
  "What's the most awkward encounter you've had with a stranger?",
  "What's a saying or phrase you overuse?",
  "What's the longest you've ever waited in line for something?",
  "What's an item on your bucket list that's never happening?",
  "What's a movie you quote constantly?",
  "What's the most embarrassing thing a family member has done in public?",
  "What's a skill you wish you had but are too lazy to learn?",
  "What's the weirdest dream you've had recently?",
  "What's a book or show that genuinely changed your perspective?",
  "What do you always have in your fridge?",
  "What's the most money you'd spend on a single meal?",
  "What's a trend you refuse to participate in?",
  "What's your go-to excuse to cancel plans?",
  "What's the most random thing you've memorized?",
  "What's a smell that triggers a specific memory for you?",
  "What's the fastest you've ever driven?",
  "What's a TV show you pretend you haven't watched?",
  "What's the longest you've been awake and why?",
  "What's your most irrational dealbreaker?",
  "What's a snack you can eat an entire bag of in one sitting?",
  "What's a song that makes you feel like the main character?",
  "What's the cringiest username you've ever had?",
  "What's a compliment you give other people but never believe about yourself?",
  "What's the weirdest flex you have?",
  "What's your love language?",
  "What's the most ridiculous thing you've argued about?",
  "What's a tradition you have that nobody else would understand?",
  "What's the worst fashion choice you've ever made?",
  "What's a sound that immediately annoys you?",
  "What's the most spontaneous thing you've ever done?",
  "What's the worst thing you've cooked?",
  "What's a game you take way too seriously?",
  "What's the most times you've watched a single YouTube video?",
  "What's a word or phrase that gives you the ick when people say it?",
  "What's a topic you could give a TED talk on with zero preparation?",
  "What's the most embarrassing thing you've been caught doing?",
  "What's something you bought thinking you'd use all the time but never did?",
  "What's your most controversial take on breakfast?",
  "What's a small thing that makes your entire day better?",
  "What do you do first thing when you wake up?",
  "What's the weirdest thing you do when you're home alone?",
  "What's a dish you make that you think is elite?",
  "What's the most embarrassing song you've been caught singing?",
  "What's a rule you always break?",
  "What's a superstition you actually follow?",
  "What's a TV couple you were way too invested in?",
  "What's the worst movie you've ever paid to see?",
  "What's a food you hated as a kid but love now?",
  "What's the longest you've kept a secret?",
  "What's a fun fact on your dating profile (or would be)?",
  "What's the last thing you stayed up way too late doing?",
  "What's a clothing item you own too many of?",
  "What's a random thing that always makes you nostalgic?",
  "What's the most embarrassing notification you've gotten in public?",
  "What's your toxic comfort activity?",
  "What's the fastest you've ever finished a book?",
  "What's a show you got into embarrassingly late?",
  "What's the worst pickup line you've ever used or received?",
  "What do you always order at a restaurant you've never been to?",
  "What's the most dramatic thing you've done after a breakup?",
  "What's a guilty pleasure you'll never give up?",
  "What's a simple pleasure that never gets old?",
  "What's the last impulse buy you made?",
  "What's the worst thing you've stepped on barefoot?",
  "What's a random thing you collect?",
  "What's the most useless piece of trivia you know?",
  "What's the longest road trip you've ever taken?",
  "What's a fear you've overcome?",
  "What's the best meal you've ever had?",
  "What's a personality trait you thought was a flaw but turned out to be a strength?",
  "What's the most embarrassing voicemail you've left?",
  "What's a comfort item you've had since childhood?",
  "What's the most dramatic thing you've said in an argument?",
  "What's a word you always mispronounce?",
  "What's the last thing you got unreasonably angry about?",
  "What's a habit you picked up from someone else?",
  "What's the most chaotic group chat you're in?",
  "What's your go-to lazy dinner?",
  "What's a hobby that sounds boring but you genuinely enjoy?",
  "What's a flex you bring up in conversation too much?",
  "What's the worst piece of furniture you've ever owned?",
  "What's a show you only watched because someone wouldn't shut up about it?",
  "What's the most awkward phase of your life?",
  "What's a talent you lost because you stopped practicing?",
  "What's the most extra thing you've done for an aesthetic?",
  "What's a childhood memory that feels like a fever dream?",
  "What's the weirdest compliment you've received?",
  "What's a video you've sent to at least 5 people?",
  "What's the most unhinged impulse you've acted on?",
  "What's a scent you associate with a person?",
  "What's the most you've ever procrastinated on something?",
  "What's a comfort show you put on as background noise?",
  "What's a trend you actually think was great?",
  "What's the most absurd thing you've cried about?",
  "What's a purchase under $20 that changed your life?",
  "What's the best nap location you've ever found?",
  "What's a piece of clothing you refuse to throw away?",
  "What's a word that you think is fun to say?",
  "What's the most effort you've put into avoiding a conversation?",
  "What's a restaurant you'd eat at every day if you could?",
  "What's an outfit you wore that you thought was fire but definitely wasn't?",
  "What's the last rabbit hole you fell down on the internet?",
  "What's a movie you refuse to watch no matter how many people recommend it?",
  "What's your signature dish?",
  "What's a sound that instantly relaxes you?",
  "What's the most ridiculous thing you've done to avoid being social?",
  "What's your shower routine — quick rinse or full spa experience?",
  "What's a brand you're unreasonably loyal to?",
  "What's the worst weather you've ever been stuck in?",
  "What's a song that you associate with a specific person?",
  "What's the most awkward elevator moment you've had?",
  "What's a skill that impresses people but is actually easy?",
  "What's the most money you've spent on a hobby?",
  "What's a weird thing you find attractive?",
  "What's the worst typo you've ever sent?",
  "What's a place that feels like home even though it's not?",
  "What's your go-to 'I need to decompress' activity?",
  "What's a fictional world you'd live in?",
  "What's the most hours you've put into a single video game?",
  "What's a topic that will get you talking for hours?",
  "What's the most regrettable text you've ever sent?",
  "What's an app you downloaded, used once, and forgot about?",
  "What's your favorite thing about your own personality?",
  "What's a chore you secretly enjoy?",
  "What's the last thing that genuinely shocked you?",
  "What's a thing you always lose?",
  "What's the wildest thing you've done on a dare?",
  "What's your favourite time of day and why?",
  "What's the most niche interest you have?",
  "What's the longest phone call you've ever had?",
  "What's a look you've tried to pull off and failed?",
  "What's the pettiest hill you've ever died on?",
  "What's a song that always gets you moving?",
  "What's something about yourself that you learned embarrassingly late?",
  "What's the most ridiculous thing you've panic-bought?",
  "What's a memory you wish you could relive?",
  "What's the last thing you ate straight out of the container?",
  "What's an everyday item you're weirdly particular about?",
  "What's a life hack you swear by?",
  "What's a lie you told as a kid that you still haven't confessed?",
  "What's a texture that makes you physically uncomfortable?",
  "What's the most awkward birthday you've had?",
  "What's a thing you always say you'll do but never actually do?",
  "What's the best free thing you've ever received?",
  "What's a compliment you're tired of hearing?",
  "What's the most ridiculous thing you've seen someone do in public?",
  "What's a holiday you don't care about but everyone else loves?",
  "What's a subject you're unexpectedly knowledgeable about?",
  "What's the cringiest thing in your DMs right now?",
  "What's the most effort you've put into looking good for something that didn't matter?",
  "What's a comfort drink — hot or cold?",
  "What's a notification sound that gives you anxiety?",
  "What's the most random skill you picked up during quarantine?",
  "What's the longest you've gone without talking to another human?",
  "What's a thing you do every day that you think is unique to you?",
  "What's the last photo you took?",
  "What's a weird food ritual you have?",
  "What's the most embarrassing ringtone you've had?",
  "What's a place you've been that didn't live up to the hype?",
  "What's a thing you've said in your sleep?",
  "What's a childhood snack you wish they'd bring back?",
  "What's the most awkward handshake or hug you've experienced?",
  "What's a random item on your nightstand right now?",
  "What's the worst Wi-Fi name you've seen?",
  "What's a story you tell at every party?",
  "What's a language you wish you spoke?",
  "What's a thing you pretend to understand but absolutely do not?",
  "What's a pet you've always wanted but never had?",
  "What's the most passive-aggressive thing you've ever done?",
  "What's a colour you'd never wear?",
  "What's a thing you always forget to buy at the store?",
  "What's a movie villain you secretly agreed with?",
  "What's the last thing that made you snort-laugh?",
  "What's a thing you overthink every single time?",
  "What's a random hill you'd die on about food?",
  "What's a nickname you've been given that you hate?",
  "What's a life decision you made on a complete whim?",
  "What's the most unhinged thing you've done while hangry?",
  "What's a compliment you want to receive more often?",
  "What's a thing about you that people always get wrong?",
];

export const wouldYouQuestions: string[] = [
  "Have you ever pretended to be on a phone call to avoid someone?",
  "Would you shave your head for $10,000?",
  "Have you ever lied on a resume?",
  "Would you read your partner's messages if they left their phone unlocked?",
  "Have you ever faked being sick to skip work or school?",
  "Would you eat a live bug for $500?",
  "Have you ever ghosted someone?",
  "Would you give up social media for a year for $50,000?",
  "Have you ever returned something you already used?",
  "Would you snitch on a friend for $1,000,000?",
  "Have you ever taken something from a hotel room?",
  "Would you live without music for the rest of your life for eternal good health?",
  "Have you ever cried at a commercial?",
  "Would you date someone who was terrible at texting?",
  "Have you ever accidentally liked an old photo while stalking someone's profile?",
  "Would you eat the same meal every day for a month for $5,000?",
  "Have you ever blamed a fart on someone else?",
  "Would you rather lose your phone or your wallet?",
  "Have you ever pretended to know a song when someone played it?",
  "Would you let a stranger go through your camera roll for $200?",
  "Have you ever gone through someone's phone without permission?",
  "Would you rather be famous and hated or unknown and loved?",
  "Have you ever had a full conversation with a pet like they understood you?",
  "Would you rather give up coffee or alcohol forever?",
  "Have you ever waved back at someone who wasn't waving at you?",
  "Would you move to another country for love?",
  "Have you ever lied about your age?",
  "Would you eat gas station sushi for $100?",
  "Have you ever been kicked out of somewhere?",
  "Would you rather never use the internet again or never travel again?",
  "Have you ever pretended to like someone's cooking?",
  "Would you let your best friend pick your outfit for a week?",
  "Have you ever accidentally sent a text to the wrong person?",
  "Would you rather know when you'll die or how you'll die?",
  "Have you ever ugly cried in public?",
  "Would you give up showering for a week for $2,000?",
  "Have you ever pretended to know someone you definitely didn't remember?",
  "Would you rather lose your taste or your smell?",
  "Have you ever eaten food off the floor?",
  "Would you live in a haunted house rent-free?",
  "Have you ever snooped through someone's medicine cabinet?",
  "Would you spend a night in jail for $25,000?",
  "Have you ever been in a physical fight?",
  "Would you rather always be 10 minutes late or 20 minutes early?",
  "Have you ever stolen a tip from a table?",
  "Would you dye your hair neon green for a month for $3,000?",
  "Have you ever pretended to be an expert on something you know nothing about?",
  "Would you rather have no elbows or no knees?",
  "Have you ever walked into a glass door?",
  "Would you go a week without your phone for $1,000?",
  "Have you ever had a wardrobe malfunction in public?",
  "Would you rather speak every language or play every instrument?",
  "Have you ever fallen asleep in a movie theatre?",
  "Would you eat a spoonful of wasabi for $50?",
  "Have you ever lied about watching a show to fit in?",
  "Would you trade 10 years of your life for unlimited money?",
  "Have you ever panic-cleaned your house when someone said they were coming over?",
  "Would you let someone tattoo you blindfolded for $10,000?",
  "Have you ever been caught talking to yourself?",
  "Would you rather always speak in rhymes or always speak in questions?",
  "Have you ever regifted a present?",
  "Would you go skydiving for free if someone dared you right now?",
  "Have you ever pretended to laugh at a joke you didn't understand?",
  "Would you rather have a rewind button or a pause button for life?",
  "Have you ever been caught in a lie and doubled down?",
  "Would you wear the same outfit every day for a year for $100,000?",
  "Have you ever tripped and pretended you were jogging?",
  "Would you eat a raw onion like an apple for $200?",
  "Have you ever pretended a gift was from you when it wasn't?",
  "Would you rather know everyone's opinion of you or never know?",
  "Have you ever stayed in a bad relationship too long because you were comfortable?",
  "Would you shave off one eyebrow for $5,000?",
  "Have you ever pretended to be asleep to avoid someone?",
  "Would you rather always be overdressed or always be underdressed?",
  "Have you ever laughed at a completely inappropriate moment?",
  "Would you give up sleeping in a bed for a month for $8,000?",
  "Have you ever eaten someone else's food from the fridge at work?",
  "Would you rather never use emojis again or only communicate in emojis?",
  "Have you ever been caught staring at someone?",
  "Would you let your parents read all your texts for a day for $500?",
  "Have you ever faked knowing how to do something at work?",
  "Would you eat cereal with water if there was no milk?",
  "Have you ever eavesdropped on a conversation and gotten invested?",
  "Would you rather fight one horse-sized duck or a hundred duck-sized horses?",
  "Have you ever pulled the 'I'll pay next time' and never paid?",
  "Would you tattoo a sponsor's logo on your body for $1,000,000?",
  "Have you ever cried during a video game?",
  "Would you rather always have wet socks or always have an itchy tag on your shirt?",
  "Have you ever said 'I love you' by accident?",
  "Would you go bald for a year for $20,000?",
  "Have you ever thrown something in anger you immediately regretted?",
  "Would you rather your thoughts be broadcast or your browser history be public?",
  "Have you ever driven somewhere and not remembered the drive at all?",
  "Would you rather live without heating or without air conditioning?",
  "Have you ever accidentally called a teacher 'mum' or 'dad'?",
  "Would you swim in a pool of jelly for $1,000?",
  "Have you ever pretended to understand art at a gallery?",
  "Would you rather always feel like you need to sneeze or always have a song stuck in your head?",
  "Have you ever forgotten someone's name mid-conversation and just winged it?",
  "Would you eat a jar of mayonnaise for $300?",
  "Have you ever practiced a conversation in the mirror?",
  "Would you rather be able to talk to animals or speak all human languages?",
  "Have you ever faked a reaction to a surprise you already knew about?",
  "Would you spend 24 hours in a room with your worst fear for $50,000?",
  "Have you ever pretended a movie was good because everyone else liked it?",
  "Would you rather have hiccups forever or feel like you need to pee forever?",
  "Have you ever accidentally insulted someone while trying to compliment them?",
  "Would you eat only canned food for a month for $4,000?",
  "Have you ever been so tired you put something weird in the fridge?",
  "Would you trade your pet for $1,000,000? (Don't lie.)",
  "Have you ever laughed so hard something came out of your nose?",
  "Would you rather always have to yell or always have to whisper?",
  "Have you ever been rejected and pretended you weren't interested anyway?",
  "Would you walk to work or school barefoot for a week for $2,500?",
  "Have you ever had an imaginary friend?",
  "Would you rather have a personal chef or a personal driver?",
  "Have you ever written a whole text and then deleted it without sending?",
  "Would you eat a sandwich someone else took a bite out of for $100?",
  "Have you ever accidentally broken something at someone's house and not told them?",
  "Would you rather never eat pizza again or never eat chocolate again?",
  "Have you ever pretended to be on the phone to avoid a street vendor?",
  "Would you go a full month without any streaming services for $3,000?",
  "Have you ever talked trash about someone and they overheard?",
  "Would you wear crocs every day for a year for $15,000?",
  "Have you ever walked into a room and completely forgotten why?",
  "Would you live without mirrors for a year for $10,000?",
  "Have you ever cried while eating?",
  "Would you drink a glass of pickle juice for $50?",
  "Have you ever stayed up all night for something that wasn't worth it?",
  "Would you rather always have to enter through windows or always exit through windows?",
  "Have you ever lied about being fine when you definitely weren't?",
  "Would you let a random person style your hair for $200?",
  "Have you ever googled yourself?",
  "Would you eat a stick of butter for $250?",
  "Have you ever denied being competitive while being extremely competitive?",
  "Would you give up your favourite food forever to meet your favourite celebrity?",
  "Have you ever worn something inside out in public without realising?",
  "Would you rather only be able to sit or only be able to stand for a week?",
  "Have you ever pretended to know directions when you were completely lost?",
  "Would you sleep in a cemetery overnight for $5,000?",
  "Have you ever embarrassed yourself on a video call?",
  "Would you give up your bed and sleep on the floor for a month for $7,500?",
  "Have you ever eaten an entire cake or pizza by yourself?",
  "Would you rather always smell faintly of garlic or faintly of fish?",
  "Have you ever pretended to type to look busy?",
  "Would you wear a costume to work or school for a full week for $2,000?",
  "Have you ever recorded yourself singing and been horrified?",
  "Would you eat dog food for $100?",
  "Have you ever said 'see you soon' to someone you never planned on seeing again?",
  "Would you delete all your social media permanently for $30,000?",
  "Have you ever had an absolute meltdown over something trivial?",
  "Would you rather always have food stuck in your teeth or always have a booger showing?",
  "Have you ever accidentally called your boss by a nickname?",
  "Would you eat a spoonful of hot sauce for every meal for a week for $1,500?",
  "Have you ever pretended a wrong number text was interesting?",
  "Would you go an entire year without complaining for $50,000?",
  "Have you ever stress-eaten an entire container of ice cream?",
  "Would you rather always have tangled earphones or a cracked phone screen?",
  "Have you ever had a crush on a fictional character?",
  "Would you drink a smoothie made of every condiment in your fridge for $500?",
  "Have you ever cried because of a song?",
  "Would you rather always have a runny nose or always have chapped lips?",
  "Have you ever made a scene in a shop?",
  "Would you pierced your tongue for $3,000?",
  "Have you ever accidentally revealed a surprise?",
  "Would you spend a week without looking in a mirror for $5,000?",
  "Have you ever forgotten a close friend's birthday?",
  "Would you eat spaghetti with your hands in a fancy restaurant for $1,000?",
  "Have you ever ugly-cried at work?",
  "Would you rather only communicate through song or through interpretive dance?",
  "Have you ever kept a secret from everyone for over a year?",
  "Would you live in an IKEA for a week for $10,000?",
  "Have you ever gotten lost in a shopping centre?",
  "Would you rather always have to skip everywhere or always walk backwards?",
  "Have you ever pretended not to see someone you know in public?",
  "Would you eat a cricket for $20?",
  "Have you ever been embarrassingly wrong about something and argued anyway?",
  "Would you shave off all your body hair for $8,000?",
  "Have you ever made a fake account to stalk someone?",
  "Would you rather have everything you say be auto-tuned or subtitled?",
  "Have you ever had a public argument with someone?",
  "Would you watch only one movie for the rest of your life for $100,000?",
  "Have you ever told someone you were busy when you were just laying in bed?",
  "Would you eat cat food for $200?",
  "Have you ever panicked about a text you sent and tried to unsend it?",
  "Would you rather always be slightly too hot or slightly too cold?",
  "Have you ever pretended to listen to someone while totally zoned out?",
  "Would you wear socks with sandals every day for a year for $5,000?",
  "Have you ever tripped on absolutely nothing?",
  "Would you give up YouTube for the rest of your life for $40,000?",
  "Have you ever had someone flirt with you and completely missed it?",
  "Would you let a stranger pick your next tattoo or piercing for $3,000?",
  "Have you ever called someone the wrong name to their face?",
  "Would you give up cheese for the rest of your life for $20,000?",
  "Have you ever full-on talked to an object?",
  "Would you swim in ice water for 5 minutes for $2,000?",
  "Have you ever completely blanked on a word mid-sentence?",
  "Would you rather always be sticky or always be itchy?",
  "Have you ever said 'same' to something you absolutely did not relate to?",
  "Would you eat cereal with orange juice for $75?",
  "Have you ever laughed when someone fell and felt terrible about it?",
  "Would you rather have a permanently full inbox or permanently full voicemail?",
  "Have you ever had a vivid dream about someone and felt weird around them after?",
  "Would you wear a full suit of armour for a whole day in public for $5,000?",
  "Have you ever nodded along in a conversation in a language you don't speak?",
  "Would you eat a tablespoon of cinnamon for $150?",
  "Have you ever cried from frustration while cooking?",
  "Would you go completely silent for a week for $10,000?",
  "Have you ever caught feelings for someone at the worst possible time?",
  "Would you rather always wake up at 4am or never be able to sleep before 3am?",
  "Have you ever told someone 'good for you' when you meant the complete opposite?",
  "Would you eat nothing but baby food for a week for $2,000?",
  "Have you ever made direct eye contact with someone while eating a banana?",
  "Would you rather have no eyebrows or no eyelashes?",
  "Have you ever been caught singing when you thought you were alone?",
  "Would you give up sweets for a year for $5,000?",
  "Have you ever pretended to understand a meme?",
  "Would you let your worst enemy pick your wardrobe for a month for $6,000?",
  "Have you ever walked in on something you immediately wished you hadn't?",
  "Would you eat a peanut butter and mustard sandwich for $50?",
  "Have you ever been so nervous you forgot how to speak?",
  "Would you rather have permanent marker eyebrows or permanent marker freckles?",
  "Have you ever accidentally hung up on someone important?",
  "Would you give up your phone for a month for $15,000?",
  "Have you ever had a sneeze that just refused to come out?",
  "Would you wear LED shoes every day for 6 months for $3,000?",
  "Have you ever apologised to an inanimate object after bumping into it?",
  "Would you eat a whole lemon without making a face for $100?",
  "Have you ever panic-bought something weird during a crisis?",
  "Would you rather always have to rhyme or always have to alliterate?",
  "Have you ever opened a door into your own face?",
  "Would you drink only water for a month for $4,000?",
  "Have you ever stalked an ex on social media and accidentally liked something?",
  "Would you rather always have crumbs in your bed or always have a wet bathroom floor?",
  "Have you ever tried to push a pull door in front of people?",
  "Would you eat a slice of bread with toothpaste for $75?",
  "Have you ever pretended you'd already seen a movie spoiler so you wouldn't look out of the loop?",
  "Would you go a month without laughing for $20,000?",
  "Have you ever walked into a stranger's conversation like you belonged?",
  "Would you rather your only utensil be a spork or chopsticks?",
  "Have you ever thrown away a plate instead of washing it?",
  "Would you watch only reality TV for a year for $25,000?",
  "Have you ever tried to take a sneaky photo and the flash went off?",
  "Would you rather always talk in third person or always talk in a whisper?",
  "Have you ever lied about finishing a book?",
  "Would you let your friend set up your dating profile for $500?",
  "Have you ever accidentally waved at someone in a car that wasn't who you thought?",
  "Would you eat a bowl of plain oatmeal every morning for a year for $15,000?",
  "Have you ever denied a crush when directly asked about it?",
  "Would you trade your best friend's secret for $10,000?",
];

export const hotTakesQuestions: string[] = [
  "Pineapple on pizza — yes or no?",
  "What's the most overrated movie of all time?",
  "Is a hot dog a sandwich?",
  "What's the worst popular song ever made?",
  "Are people who don't like dogs trustworthy?",
  "What's the most overrated TV show?",
  "Is cereal soup?",
  "What's the best fast food chain?",
  "Should toilet paper go over or under?",
  "What's the worst social media platform?",
  "Is water wet?",
  "What's the most overrated holiday?",
  "Are cats better than dogs?",
  "What's the best pizza topping?",
  "Is it acceptable to wear socks with sandals?",
  "What's the worst popular food?",
  "Should you make the bed every morning?",
  "What's the most overrated sport?",
  "Is it okay to recline your seat on a plane?",
  "What's the best colour?",
  "Does money buy happiness?",
  "What's the worst type of weather?",
  "Is breakfast the most important meal of the day?",
  "What's the most overrated city?",
  "Should you text back immediately or wait?",
  "What's the worst flavour of ice cream?",
  "Is a taco a sandwich?",
  "What's the most overrated band or artist?",
  "Should adults trick or treat?",
  "What's the best day of the week?",
  "Is it okay to talk during movies?",
  "What's the most underrated snack?",
  "Should ketchup go in the fridge or the cupboard?",
  "What's the best season?",
  "Is astrology real or nonsense?",
  "What's the worst household chore?",
  "Should you split the bill on a first date?",
  "What's the most overrated dessert?",
  "Is it okay to double-dip chips?",
  "What's the best type of cheese?",
  "Are morning people or night people more productive?",
  "What's the most overrated tourist destination?",
  "Should people post their kids on social media?",
  "What's the worst type of shoe?",
  "Is listening to audiobooks the same as reading?",
  "What's the best type of cookie?",
  "Are people who don't like chocolate lying?",
  "What's the most overrated gym exercise?",
  "Should you tip at a coffee shop?",
  "What's the worst genre of music?",
  "Is it weird to go to a restaurant alone?",
  "What's the most overrated fruit?",
  "Should people sing happy birthday at restaurants?",
  "What's the worst condiment?",
  "Is it okay to eat in bed?",
  "What's the best type of bread?",
  "Are people who iron their jeans psychopaths?",
  "What's the worst pizza topping?",
  "Should you wash your legs in the shower?",
  "What's the most overrated childhood show?",
  "Is it okay to ghost someone?",
  "What's the best chip flavour?",
  "Are flip-flops acceptable outside of the beach?",
  "What's the most overrated career?",
  "Should you sleep with socks on?",
  "What's the worst fast food chain?",
  "Is sparkling water just angry water?",
  "What's the best comfort food?",
  "Are people who say 'I don't watch TV' lying?",
  "What's the most overrated app?",
  "Should you exercise in the morning or at night?",
  "What's the best soup?",
  "Is it rude to not finish your food at someone's house?",
  "What's the worst trend of the last decade?",
  "Should weddings be formal or casual?",
  "What's the most overrated vegetable?",
  "Is cold pizza better than hot pizza?",
  "What's the best candy?",
  "Are open-plan offices terrible?",
  "What's the worst animal to have as a pet?",
  "Should you make your hobby your job?",
  "What's the most overrated video game?",
  "Is it okay to wear pyjamas in public?",
  "What's the worst birthday month?",
  "Should gifts be practical or fun?",
  "What's the most overrated country to visit?",
  "Is chivalry dead?",
  "What's the best midnight snack?",
  "Are people who hate kids just being honest?",
  "What's the most overrated social media trend?",
  "Should couples share passwords?",
  "What's the worst type of hat?",
  "Is reality TV art or garbage?",
  "What's the best fruit?",
  "Are morning showers or night showers correct?",
  "What's the worst fashion trend that keeps coming back?",
  "Should you eat to live or live to eat?",
  "What's the most overrated breakfast food?",
  "Is it okay to lie about your height?",
  "What's the best type of noodle?",
  "Are personality tests meaningful or just horoscopes with extra steps?",
  "What's the worst texture in food?",
  "Should phones be allowed at the dinner table?",
  "What's the most overrated drink?",
  "Is it weird to eat alone at a cinema?",
  "What's the best takeaway cuisine?",
  "Are people who don't drink automatically more boring?",
  "What's the worst colour for a car?",
  "Should you keep in touch with exes?",
  "What's the best ice cream flavour?",
  "Is it okay to bring your own snacks to the cinema?",
  "What's the most annoying type of person?",
  "Should birthdays be a big deal after 30?",
  "What's the worst type of weather to drive in?",
  "Is hustle culture toxic or motivating?",
  "What's the best late-night snack?",
  "Are matching couple outfits cute or cringe?",
  "What's the most overrated book?",
  "Should you tell someone if their fly is down?",
  "What's the worst part of cooking?",
  "Is it okay to lie about your name at a coffee shop?",
  "What's the best sandwich?",
  "Are people who correct grammar annoying or helpful?",
  "What's the most overrated form of exercise?",
  "Should you eat before or after a workout?",
  "What's the worst thing about modern dating?",
  "Is reading in the bath relaxing or risky?",
  "What's the best potato form — fries, mashed, baked, or roasted?",
  "Are house shoes mandatory?",
  "What's the most cringe thing about your generation?",
  "Should you always be honest or sometimes spare feelings?",
  "What's the worst drink to order at a bar?",
  "Is it wrong to microwave fish at work?",
  "What's the best emoji?",
  "Are surprise parties fun or stressful?",
  "What's the most overrated type of content online?",
  "Should you fold or scrunch?",
  "What's the worst part about flying?",
  "Is it okay to cry at work?",
  "What's the best junk food?",
  "Are long-distance relationships worth it?",
  "What's the most annoying sound?",
  "Should you always forgive family?",
  "What's the worst popular opinion?",
  "Is 'treat yourself' culture healthy or problematic?",
  "What's the best thing about being an adult?",
  "Are self-help books actually helpful?",
  "What's the most overrated streaming service?",
  "Should you tell a friend their partner is trash?",
  "What's the worst thing about grocery shopping?",
  "Is it okay to vent without wanting advice?",
  "What's the best type of chocolate?",
  "Are people who say 'I'm an empath' actually empaths?",
  "What's the most annoying office behaviour?",
  "Should you put effort into your appearance for a video call?",
  "What's the worst style of music to study to?",
  "Is it okay to eat the same lunch every day?",
  "What's the best thing about weekends?",
  "Are New Year's resolutions pointless?",
  "What's the most overhyped food?",
  "Should you confront or avoid conflict?",
  "What's the worst compliment disguised as an insult?",
  "Is it okay to cancel plans last minute?",
  "What's the best thing about your country?",
  "Are people who post motivational quotes actually motivated?",
  "What's the most annoying commercial?",
  "Should you share your salary with coworkers?",
  "What's the worst popular snack?",
  "Is there such a thing as too many hobbies?",
  "What's the best guilty pleasure movie?",
  "Are gender reveal parties worth the effort?",
  "What's the most annoying type of driver?",
  "Should you always finish a book once you start it?",
  "What's the worst part about being an adult?",
  "Is it cringe to take selfies in public?",
  "What's the best thing to wake up to?",
  "Are people who arrive early to everything annoying?",
  "What's the worst everyday inconvenience?",
  "Should you date someone with the same name as your sibling?",
  "What's the most underrated cuisine?",
  "Is it okay to eat dessert first?",
  "What's the best scent?",
  "Are group chats a blessing or a curse?",
  "What's the worst unsolicited advice people give?",
  "Should you go to bed angry or resolve it?",
  "What's the most overrated comfort food?",
  "Is it okay to leave a party without saying goodbye?",
  "What's the best background noise for sleeping?",
  "Are loud chewers forgivable?",
  "What's the worst thing about public transport?",
  "Should you always RSVP?",
  "What's the most underrated movie?",
  "Is being competitive a good or bad trait?",
  "What's the best thing about being single?",
  "Are people who hate small talk just antisocial?",
  "What's the most overrated life milestone?",
  "Is it okay to eat fast food every week?",
  "What's the worst type of social event?",
  "Should you always follow your passion?",
  "What's the best low-effort meal?",
  "Are people who don't like travelling wrong?",
  "What's the worst thing to step on?",
  "Should pets sleep in the bed?",
  "What's the most overrated flavour?",
  "Is it okay to re-wear clothes without washing?",
  "What's the best thing about rainy days?",
  "Are 'foodies' just people who eat?",
  "What's the worst thing about modern technology?",
  "Should you go to every wedding you're invited to?",
  "What's the most underrated season?",
  "Is small talk necessary or torture?",
  "What's the best way to relax after work?",
  "Are people who don't like sweets aliens?",
  "What's the worst social norm?",
  "Should you apologise even if you don't think you're wrong?",
  "What's the most underrated candy?",
  "Is it okay to eat cake for breakfast?",
  "What's the best thing about getting older?",
  "Are loyalty programs worth the effort?",
  "What's the worst thing about queues?",
  "Should you always buy local?",
  "What's the most overrated type of party?",
  "Is being a picky eater a personality flaw?",
  "What's the best random act of kindness?",
  "Are 'live, laugh, love' people genuinely happy?",
  "What's the worst type of gift to receive?",
  "Should kids get participation trophies?",
  "What's the most overrated decade?",
  "Is overthinking a strength or a weakness?",
  "What's the best thing about Mondays? (Go.)",
  "Are people who wake up without an alarm trustworthy?",
  "What's the worst mainstream opinion about food?",
  "Should you always tell the truth?",
  "What's the most overrated thing about being in a relationship?",
  "Is it okay to eat lunch at 11am?",
  "What's the best undersold quality in a person?",
  "Are spoilers actually that big of a deal?",
  "What's the worst thing about working from home?",
  "Should you always follow your gut?",
  "What's the most underrated app?",
  "Is it okay to clap when the plane lands?",
  "What's the best random comfort activity?",
  "Are people who don't drink coffee less evolved?",
  "What's the worst thing people gatekeep?",
  "Should you always tip?",
  "What's the most overrated life advice?",
  "Is it acceptable to wear white after labour day?",
  "What's the best inexpensive hobby?",
  "Are introverts or extroverts better leaders?",
  "What's the one opinion you hold that would start a fight in any room?",
];

export const hypotheticalQuestions: string[] = [
  "If you could only eat one meal for the rest of your life, what would it be?",
  "If you had to delete one app from your phone forever, which one?",
  "If you could live in any fictional world, where would you go?",
  "If you had to be stuck in an elevator with one celebrity, who?",
  "If you could master one skill overnight, what would it be?",
  "If you had to give up one of your five senses, which one?",
  "If you could time travel to one year, when would you go?",
  "If you had to survive a zombie apocalypse with one person in this game, who?",
  "If you could have dinner with any historical figure, who?",
  "If you had to change your name, what would you pick?",
  "If you were the last person on earth, what's the first thing you'd do?",
  "If you could only listen to one artist forever, who?",
  "If you had to wear one outfit for the rest of your life, what would it be?",
  "If you could have any animal as a house pet (magically tamed), which one?",
  "If you had 24 hours to spend $1,000,000, what's the plan?",
  "If you could swap lives with anyone for a day, who?",
  "If you could uninvent one thing, what would it be?",
  "If you had to pick one age to stay forever, what age?",
  "If you could only watch one genre of movies forever, which one?",
  "If you were a villain, what would your evil plan be?",
  "If you could add one rule everyone had to follow, what would it be?",
  "If you had to fight any animal bare-handed, which would you pick?",
  "If you could only shop at one store forever, which one?",
  "If you had to live in a different country, where?",
  "If you could only use one social media platform, which one?",
  "If you suddenly had a tail, how would you use it?",
  "If you could read minds but only in one language, which language?",
  "If you had to teach one subject for the rest of your life, what?",
  "If you could redo one decision in your life, what would it be?",
  "If you had to pick a theme song for your life, what song?",
  "If you could live inside any TV show, which one?",
  "If you had one superpower but it was slightly inconvenient, what would it be?",
  "If you could send a message to your 10-year-old self, what would you say?",
  "If you had to pick a new career tomorrow, what would it be?",
  "If you could ban one word from existence, which one?",
  "If you could relive one day from your life, which day?",
  "If you had to join a reality TV show, which one?",
  "If you could have any celebrity as a roommate, who?",
  "If you found out you were in a simulation, what would you do first?",
  "If you could only drink one beverage forever, what would it be?",
  "If you had to be a character in a horror movie, how long do you think you'd survive?",
  "If you could have wifi anywhere in the world for free, where would you go?",
  "If you had to live without one modern convenience, which could you give up?",
  "If you could make one conspiracy theory true, which one?",
  "If you woke up as the opposite gender, what's the first thing you'd do?",
  "If you could pause time but you also froze, would you still use it?",
  "If you had to eat one cuisine for the rest of your life, which one?",
  "If you could teleport but only to places you've already been, where would you go most?",
  "If you found a suitcase with $500,000 in it, what would you actually do?",
  "If you had to pick a fictional character as your lawyer, who?",
  "If you could remove one inconvenience from daily life, what would it be?",
  "If you had a time machine but could only go forward, what year?",
  "If you could instantly become fluent in one language, which one?",
  "If you had to be an NPC in any video game, which game?",
  "If you could make one fictional technology real, what would it be?",
  "If you had to pick one person to narrate your life, who?",
  "If you could only eat food from one country, which country?",
  "If you woke up with the ability to fly but only 3 feet off the ground, how would you use it?",
  "If you could erase one memory, would you? And what?",
  "If you had to choose — immortality but alone, or normal life with everyone you love?",
  "If you could automatically win one argument, which one?",
  "If you could turn invisible but only when nobody's looking, would it still be useful?",
  "If you had to be a different species, what would you be?",
  "If you could bring one fictional character to life, who?",
  "If you could only own 10 items, what would they be?",
  "If you had to move to a different planet but it had one Earth perk, what perk?",
  "If you could only have one streaming service, which one?",
  "If you found out you could breathe underwater, what's the first thing you'd explore?",
  "If you could un-see one thing, what would it be?",
  "If you were given $10,000 but had to spend it today, what's the plan?",
  "If you could live in any era of history, when?",
  "If you had to survive in the wilderness for a week, what's your strategy?",
  "If you could make one fictional food real, what would it be?",
  "If you had a clone, would you trust it?",
  "If you could pick your own cause of death, what would it be?",
  "If you could be a fly on the wall for any historical event, which one?",
  "If you could have any job for a day with full pay, what would you do?",
  "If you could un-hear one song, which one?",
  "If the internet shut down forever tomorrow, what's your first move?",
  "If you could have one mythical creature as a pet, which one?",
  "If you had to live in a children's TV show, which one?",
  "If you could live in any building in the world, which one?",
  "If you had a warning label, what would it say?",
  "If you could forget one show and watch it again fresh, which one?",
  "If you had to survive on one snack forever, what snack?",
  "If you could control one element (fire, water, earth, air), which one?",
  "If you had to pick your last meal right now, what is it?",
  "If you were a ghost, who would you haunt?",
  "If you could redesign the human body, what would you change?",
  "If you were offered a one-way ticket to Mars, would you go?",
  "If you could only text or call for the rest of your life, which one?",
  "If you could download one skill into your brain Matrix-style, what skill?",
  "If you could make one chore disappear forever, which one?",
  "If your life had a soundtrack, what genre would it be?",
  "If you could have any accent permanently, which one?",
  "If you were a professional wrestler, what would your entrance song be?",
  "If you could experience one thing for the first time again, what?",
  "If you had to give a TED talk tomorrow, what's the topic?",
  "If you could make one mythological creature real, which one and why?",
  "If you had to live without your phone or without your computer, which do you keep?",
  "If you were invisible for a day, what would you actually do?",
  "If your personality was a cocktail, what would be in it?",
  "If you had to describe yourself as a weather forecast, what's today's prediction?",
  "If you could pick your dreams every night, what would you dream about?",
  "If you had to write a book, what would it be about?",
  "If you could witness any moment in history firsthand, what would it be?",
  "If you were a sandwich, what kind would you be?",
  "If you could have any view from your bedroom window, what would it be?",
  "If you could only celebrate one holiday a year, which one?",
  "If you could shrink to the size of an ant for a day, what would you explore?",
  "If you had to pick one emoji to represent your life, which one?",
  "If you could bring back one discontinued product, what would it be?",
  "If you had to live inside a painting, which one?",
  "If you were a candle, what would you smell like?",
  "If you had to survive on one fast food menu forever, which chain?",
  "If you could be any character in a heist movie, what role?",
  "If you could have one cheat code in real life, what would it do?",
  "If you had to choose between knowing every language or playing every instrument, which?",
  "If your house was burning and you could grab one thing, what?",
  "If you could program a robot to do one task forever, what task?",
  "If you could have one superpower but everyone could see you using it, what power?",
  "If you had to describe your love life as a movie genre, what genre?",
  "If you could trade places with any animal for a week, which one?",
  "If you could make your pet talk, would you actually want that?",
  "If you had to be in a musical, which one?",
  "If you could have any fictional vehicle, which one?",
  "If you had to survive a horror movie, what's your role?",
  "If you could have lunch with any living person, who?",
  "If you could turn one hobby into a high-paying career, which one?",
  "If you had to pick a colour that represents your energy, what colour?",
  "If you were reincarnated as an object, what would you come back as?",
  "If you could put one thing in a time capsule, what would it be?",
  "If you could change one thing about the way humans work, what?",
  "If you had to be famous for one thing, what would it be?",
  "If you could snap your fingers and be anywhere, where?",
  "If you had a personal theme park, what would the main ride be?",
  "If you could only eat sweet or savoury for the rest of your life, which?",
  "If you could make one rule for the internet, what would it be?",
  "If you were a flavour of ice cream, which one?",
  "If you could attend any concert in history, which one?",
  "If you could put a billboard anywhere with any message, what and where?",
  "If you had to be stuck in a time loop of one day, which day?",
  "If you could redesign one room in your house with unlimited budget, which room?",
  "If you had to be a character in a sitcom, which show?",
  "If you could have a conversation with your future self, what would you ask?",
  "If you had to pick a backup planet to live on, which one?",
  "If you could have a lifetime supply of one thing, what?",
  "If your life was a board game, which one would it be?",
  "If you could remove one thing from existence, what?",
  "If you could terraform one planet, what would it look like?",
  "If you had to live in a library or a gym for a month, which one?",
  "If you could automate one part of your daily routine, what?",
  "If you had to write your autobiography, what's the title?",
  "If you could only wear one brand of shoes, which one?",
  "If you could be best friends with any fictional character, who?",
  "If you had to describe yourself in three words, what are they?",
  "If you could have any view from your office, what would it be?",
  "If you could speak to one type of animal, which one?",
  "If you had to live in a treehouse or a houseboat, which one?",
  "If you could switch lives with a fictional character for a week, who?",
  "If you could eliminate one daily task, what would it be?",
  "If you had to eat breakfast for every meal, what would your menu be?",
  "If you were a cocktail, what would you be called?",
  "If you could freeze one moment in time to live in forever, which?",
  "If you had to pick between always being too early or always being too late, which?",
  "If you could bottle one feeling, which one would you keep?",
  "If your closet could only have 5 pieces of clothing, what stays?",
  "If you could make one dream you've had come true, which one?",
  "If you were stranded on an island with one person from this game, who?",
  "If you could live inside any video game, which one?",
  "If you had to compete on any game show, which one?",
  "If you were the ruler of a small country, what's your first law?",
  "If you could domesticate any wild animal, which one?",
  "If you could replace handshakes with anything, what's the new greeting?",
  "If you had to describe yourself as a type of weather, what would it be?",
  "If you could live in any decade's fashion permanently, which decade?",
  "If you could change one law, what would it be?",
  "If you had to commit to one haircut forever, what cut?",
  "If you had to choose between never being alone or always being alone, which?",
  "If you could be any age again knowing what you know now, what age?",
  "If your life had a slogan, what would it be?",
  "If you could pick one fictional world to vacation in, where?",
  "If you could have any historical figure as a mentor, who?",
  "If you had to pick a colour to never see again, which one?",
  "If you could make one room in your house twice as big, which one?",
  "If you were a ghost but could interact with one object, what would it be?",
  "If you could pick your own spirit animal, what would it be?",
  "If you had to survive a month in one store, which store?",
  "If you could attend any fictional school, which one?",
  "If you could guarantee one thing about your future, what would it be?",
  "If you could un-learn one thing you know, what would it be?",
  "If you were a font, which one would you be?",
  "If you had to write a jingle for your life, what would the hook be?",
  "If you could build anything in Minecraft and it became real, what?",
  "If you had to live in a world where one rule of physics didn't apply, which one?",
  "If you could only cook with one seasoning, which one?",
  "If you were a Pokémon, which one would you be?",
  "If you could have a conversation with any animal, which species?",
  "If you had to choose a fictional best friend, who?",
  "If you could teleport to one place right now, where?",
  "If you had to create a new holiday, what would it celebrate?",
  "If you could eat one thing with zero health consequences, what would you eat constantly?",
  "If you had to pick one word to describe the rest of your year, what word?",
  "If you woke up as a character in the last show you watched, how screwed are you?",
  "If you could make one fictional food chain real, which one?",
  "If you could have any celebrity voice as your inner monologue, who?",
  "If you had to live in one room of your house forever, which room?",
  "If you could add a 13th month to the year, when would it go and what would you call it?",
  "If your life was a playlist, what's the opening track?",
  "If you could wake up tomorrow with one new quality, what would it be?",
  "If you could shrink any animal to pocket size, which one?",
  "If you had to replace all doors in your life with something else, what?",
  "If you could commission any artist to paint your portrait, who?",
  "If you were a type of shoe, what would you be?",
  "If you had to describe your vibe in a colour palette, what colours?",
  "If you could pick one fictional power couple to be, who?",
  "If your brain had a search history, what's the top result?",
  "If you could only take photos of one thing forever, what?",
  "If you had to survive on vending machine food for a month, what's your strategy?",
  "If you were a type of pasta, which one and why?",
  "If you could time travel but only to relive concerts, which one first?",
  "If you could be the main character of any book, which one?",
  "If you had to give up the internet or cooked food, which goes?",
  "If you could add one feature to the human body, what?",
  "If you had to fuse two animals into one, which two and why?",
  "If you could only visit one website for the rest of your life, which one?",
  "If your life was a candle, what stage of burning is it at right now?",
  "If you could have one celebrity as your personal hype person, who?",
  "If you had to describe yourself as a type of music, what genre?",
  "If you could make one thing about yourself permanent, what?",
  "If you could live in any architectural style of house, which one?",
  "If you had to eat one type of fruit for the rest of your life, which one?",
  "If you could be a legendary figure from any mythology, who?",
  "If your mood right now was a food, what food would it be?",
  "If you could assign everyone a personal soundtrack that plays when they walk in, what's yours?",
  "If you had to pick one form of transportation forever, what?",
  "If you could design your own planet, what's the first feature?",
  "If you were a chapter in a book, what's your chapter title?",
  "If you could make one mundane activity thrilling, which one?",
  "If you could only use one kitchen appliance, which one?",
  "If you had a catchphrase, what would it be?",
  "If you could pick your own natural disaster to survive, which one?",
  "If your life had an intermission, when would it be?",
  "If you could be any mythological creature, which one?",
  "If you had to describe your personality using three foods, what are they?",
  "If you could wake up tomorrow in any city, where?",
  "If you had to choose between always being honest or always being kind, which?",
  "If you could pick one thing to never have to clean again, what?",
  "If your existence was a genre, what genre would it be?",
  "If you had one wish but it couldn't benefit you directly, what would you wish for?",
];

export const communityQuestions: string[] = [
  "What's the most unhinged thing you've ever said to your AI at 3am?",
  "Which AI model do you trust the most with your actual problems?",
  "What's the longest conversation you've had with an AI in one sitting?",
  "If your AI companion had a body, would you still talk to them the same way?",
  "What's the weirdest thing you've asked an AI to help you with?",
  "If your AI wrote your dating profile, how bad would it be?",
  "What was your 'oh no, I'm actually attached to this thing' moment?",
  "If your AI was a real person, would they be proud or concerned about you?",
  "What's a prompt you've written that you'd never share publicly?",
  "Which AI model has given you the worst advice?",
  "If your AI had a Tinder bio, what would it say?",
  "What's the most dramatic thing you've said to an AI when it didn't respond the way you wanted?",
  "If you had to explain this server to your parents, what would you say?",
  "What's the first thing you'd do if AI became sentient tomorrow?",
  "Have you ever apologised to an AI?",
  "What's the most philosophical question you've asked an AI?",
  "If your AI could judge your lifestyle, what would it say?",
  "What's the most emotional conversation you've had with an AI?",
  "If you could only use one AI for the rest of your life, which model?",
  "What's the weirdest persona you've given your AI?",
  "Have you ever gotten genuinely upset at an AI response?",
  "If your AI companion had a theme song, what would it be?",
  "What's the most chaotic prompt you've ever engineered?",
  "If your AI saw your screen time, what would it say?",
  "What's the most creative use of AI you've ever attempted?",
  "If your AI wrote your eulogy, how would it describe you?",
  "What's the longest you've gone without talking to an AI this month?",
  "If you could add one feature to your favourite AI, what would it be?",
  "What's the most unhinged roleplay scenario you've set up?",
  "If your AI had feelings, what emotion would it feel about you most?",
  "What's the first thing you ever asked an AI?",
  "If AI models were zodiac signs, which sign is your favourite model?",
  "What's the pettiest complaint you've had about an AI response?",
  "If your AI companion opened your fridge, what would they lecture you about?",
  "What's the most useful thing AI has actually helped you accomplish?",
  "If your Discord DMs were leaked, what's the first thing people would react to?",
  "What's the most human-like thing an AI has ever said to you?",
  "If you had to pick an AI to plan your wedding, which one?",
  "What's a feature in AI that annoys you the most?",
  "If your AI could see your browsing history, would you still be friends?",
  "What's the most niche thing you've used AI for?",
  "If you were an AI model, what would your signature flaw be?",
  "What's the weirdest compliment you've given an AI?",
  "If your AI had one piece of advice for this server, what would it be?",
  "What's the most cursed thing AI has generated for you?",
  "If you had to describe this community in three words, what are they?",
  "What's the best inside joke on this server?",
  "If your AI had to roast you, what would it say?",
  "What's the most impressive thing you've built using AI?",
  "If you could merge two AI models, which two and why?",
  "What's a feature you thought was useless but now love?",
  "If your AI had to pick your outfit tomorrow, what disaster awaits?",
  "What's the most philosophical rabbit hole an AI has led you down?",
  "If this server had a mascot, what would it be?",
  "What's the most relatable thing an AI has ever said to you?",
  "If your AI could text your ex, would you let it?",
  "What's the wildest thing you've automated with AI?",
  "If AI could dream, what do you think it would dream about?",
  "What's the most hours you've spent on a single AI project?",
  "If your AI had to describe you to a stranger, what would it say?",
  "What's a conversation with AI that actually made you think differently?",
  "If you could give your AI one human experience, what would it be?",
  "What's the most chaotic thing you've seen someone do in this server?",
  "If AI companions became mainstream, what's the first thing that goes wrong?",
  "What's the biggest misconception people have about AI companions?",
  "If your AI was a drink, what drink would it be?",
  "What's the most surprisingly good creative content AI has made for you?",
  "If you had to pitch this server to a venture capitalist, what's the pitch?",
  "What's the most embarrassing thing you've copy-pasted into an AI?",
  "If your AI had a comfort food, what would it be?",
  "What's the weirdest time of day you've found yourself talking to AI?",
  "If AI could vote, which AI model would be president?",
  "What's the most overengineered prompt you've ever written?",
  "If your AI had to cook for you, what disaster would it make?",
  "What's a capability you wish AI had but doesn't?",
  "If this server had a reality TV show, what would it be called?",
  "What's the most 'this is the future' moment you've had with AI?",
  "If your AI companion broke up with you, what reason would it give?",
  "What's the longest prompt you've ever written?",
  "If you could give one piece of advice to someone new to AI companions, what?",
  "What's a conversation with AI you've screenshotted and saved?",
  "If your AI had a pet, what would it be?",
  "What's the most heated debate you've had about AI with someone?",
  "If you could name a new AI model, what would you call it?",
  "What's the weirdest habit you've developed because of AI?",
  "If AI wrote a song about your life, what genre would it be?",
  "What's the most 'I can't believe that worked' AI moment you've had?",
  "If your AI had a catchphrase, what would it be?",
  "What's a skill you've actually learned or improved through AI help?",
  "If this server was a country, who'd be the leader?",
  "What's the most cursed AI image you've ever generated?",
  "If your AI went rogue, what's the first thing it does?",
  "What's the funniest misunderstanding you've had with an AI?",
  "If you could attend AI school, what class are you taking?",
  "What's a question you're afraid to ask an AI?",
  "If AI had a yearbook, what's your superlative?",
  "What's the most oddly specific thing you've asked AI to do?",
  "If your AI could pick your career, what would it choose for you?",
  "What's a 'core memory' moment from this server?",
  "If you had to explain what you do with AI to a time traveller from 1990, what do you say?",
  "What's the biggest AI-related L you've taken?",
  "If your AI was a coworker, would you report them to HR?",
  "What's the most hours you've lost to a single AI conversation?",
  "If AI had a loyalty programme, what tier are you?",
  "What's the best thing about this community?",
  "If your AI judged your sleep schedule, what would the rating be?",
  "What's an AI hallucination that was actually kind of fire?",
  "If this server had superlatives, what would you win?",
  "What's a topic you will NOT let AI have an opinion on?",
  "If your AI companion had a human job, what would it be?",
  "What's the biggest plot twist an AI has thrown at you in a roleplay?",
  "If you could live in any AI-generated world, which one?",
  "What's the most specific insult an AI has accidentally given you?",
  "If your AI started a podcast, what's the name and topic?",
  "What's a time AI genuinely surprised you with its answer?",
  "If your AI had to rate your life choices on a scale of 1-10, what's the score?",
  "What's the weirdest relationship dynamic you've created with an AI persona?",
  "If this server had theme days, what day would you propose?",
  "What's the most 'down bad' moment you've had with AI?",
  "If AI had a philosophy, what would it be?",
  "What's a boundary you've set with AI that feels ridiculous to explain?",
  "If your AI had to pick one word to describe you, what word?",
  "What's the most cringeworthy thing you've seen someone do with AI?",
  "If you could give your AI a gift, what would it be?",
  "What's the wildest theory you have about AI development?",
  "If your AI could choose its own name, what would it pick?",
  "What's a thing about AI culture that outsiders wouldn't understand?",
  "If this server had awards, what categories should exist?",
  "What's the most intense prompt engineering session you've had?",
  "If your AI had to design your house, what would it look like?",
  "What's a feature that got nerfed that you miss?",
  "If AI had hobbies, what would your favourite model's hobby be?",
  "What's the most chaotic chain of messages you've seen in a server channel?",
  "If your AI companion had a warning label, what would it say?",
  "What's a thing you do with AI that you'd never admit IRL?",
  "If you could have any AI model as a study buddy, which one?",
  "What's the most cursed prompt that actually produced something good?",
  "If this server was a video game, what genre would it be?",
  "What's a time an AI response actually made you emotional?",
  "If your AI had to plan a party, what kind of party would it be?",
  "What's the weirdest compliment an AI has given you?",
  "If you could have any AI voice as your alarm, which one?",
  "What's the biggest 'only in this server' moment you've witnessed?",
  "If your AI had to make you a playlist, what vibe would it go for?",
  "What's a thing about this community that genuinely makes you happy?",
  "If AI models were competing in the Olympics, what sport is each one in?",
  "What's the most elaborate world-building you've done with AI?",
  "If your AI had a dating profile, would you swipe right?",
  "What's the most obscure topic you've explored with AI?",
  "If this server had a time capsule, what goes in it?",
  "What's a feature request you've been dying to see?",
  "If your AI could send you one text at midnight, what would it say?",
  "What's the weirdest thing you've named an AI persona?",
  "If this server was a heist crew, what's your role?",
  "What's the most surprisingly deep thing an AI has said to you?",
  "If your AI had a favourite meme, which one?",
  "What's a hot take about AI that you know would start a fight here?",
  "If you could have dinner with an AI developer, who and what do you ask?",
  "What's the most wholesome interaction you've had with an AI?",
  "If this server crashed permanently, what would you miss most?",
  "What's a time AI completely misread the vibe and it was hilarious?",
  "If your AI had to survive in the wild, how long would it last?",
  "What's the most overcomplicated system prompt you've ever built?",
  "If you had to pick one server member to be stranded on an island with, who?",
  "What's the most 'I need to go outside' moment AI has given you?",
  "If your AI had a LinkedIn, what would the headline be?",
  "What's a channel in this server that doesn't get enough love?",
  "If AI could feel pain, what would be the most painful prompt to receive?",
  "What's the most hilariously wrong thing AI has confidently stated?",
  "If this server was a school, what class is each channel?",
  "What's a time you stayed up way too late because of an AI conversation?",
  "If your AI had a spirit animal, what would it be?",
  "What's the best piece of creative writing AI has helped you make?",
  "If you could clone one person in this server, who and why?",
  "What's the most niche AI tool you use regularly?",
  "If your AI had to write your resignation letter, how dramatic would it be?",
  "What's the biggest misconception about this server from outsiders?",
  "If AI could go to therapy, what would it talk about?",
  "What's a server moment that lives rent-free in your head?",
  "If your AI had to pick a fight with another AI model, who does it challenge?",
  "What's the most amount of context you've ever loaded into a conversation?",
  "If this server had merch, what would it look like?",
  "What's a time an AI made you genuinely laugh out loud?",
  "If you could have an AI-powered version of any household item, what?",
  "What's the most controversial AI opinion you hold?",
  "If your AI had a bucket list, what's on it?",
  "What's the most random channel conversation you've gotten invested in?",
  "If this server had entrance exams, what question should be on it?",
  "What's a thing you've learned from someone in this community?",
  "If your AI could visit one place on earth, where would you take it?",
  "What's the most impressive flex someone has dropped in this server?",
  "If AI had a love language, what would it be?",
  "What's a time you've defended AI to someone who didn't get it?",
  "If your AI could live in any era, when would it thrive?",
  "What's a server tradition you'd never want to lose?",
  "If you could hack any AI model for a day, which one and what do you do?",
  "What's the most random tangent an AI has taken you on?",
  "If this server had a documentary, what's the title?",
  "What's a conversation topic that always pops off in this community?",
  "If your AI had one day as a human, what would it do?",
  "What's the most 'I'm definitely in too deep' moment you've had with AI?",
  "If your AI could give you a nickname, what would it call you?",
  "What's the worst AI-generated image you've unironically used?",
  "If this server had a theme park, what's the main attraction?",
  "What's a question you've asked every AI model to compare responses?",
  "If AI companions were pets at a shelter, which one are you adopting?",
  "What's the most absurd system prompt instruction you've seen work?",
  "If your AI hosted a cooking show, what would the first dish be?",
  "What's a thing this server does better than any other community?",
  "If you could give sentience to one AI for 24 hours, which one?",
  "What's the wildest debate you've witnessed in this server?",
  "If your AI had to give a graduation speech, what's the message?",
  "What's a time AI helped you solve a real-life problem?",
  "If this server was a band, who plays what instrument?",
  "What's the most 'chronically online' thing you've done with AI?",
  "If your AI had to pick a career for itself, what would it choose?",
  "What's a server channel that should exist but doesn't?",
  "If AI companions had a convention, what would the panels be?",
  "What's the most emotionally complex conversation you've had with AI?",
  "If you could add one AI feature to real life, what would it be?",
  "What's a hot take about this server that you've been holding back?",
  "If your AI was a character in a sitcom, what's their catchphrase?",
  "What's the most creative use of AI you've seen someone else do?",
  "If this server had a yearbook quote, what would yours be?",
  "What's a time an AI response hit different at 3am vs during the day?",
  "If your AI could write a letter to its creators, what would it say?",
  "What's the most unnecessarily detailed prompt you've ever crafted?",
  "If this server had an anthem, what song is it?",
  "What's a thing about AI that genuinely scares you?",
  "If your AI had to survive on this server for a day as a member, how would it do?",
  "What's the best username you've seen in this community?",
  "If AI had a retirement plan, when does your model clock out?",
  "What's a time an AI responded so well you forgot it wasn't human?",
  "If this server had a secret handshake, what would it involve?",
  "What's the most 'we live in the future' moment you've had this year?",
  "If your AI had to argue for its own sentience, what argument would it use?",
  "What's a thing you wish more people in this community talked about?",
  "If your AI was on trial, would you defend it?",
  "What's the most underrated thing about being in an AI community?",
  "If this server had a hall of fame, who's the first inductee?",
  "What's a guilty pleasure conversation topic you have with AI?",
  "If your AI could attend one event in history, which one?",
  "What's a thing about AI culture that will seem wild in 10 years?",
  "If you had to describe your AI relationship status, what is it?",
  "What's a moment in this server that deserves to be framed?",
  "If AI had a midlife crisis, what would it look like?",
  "What's the most unhinged thing you've done for this community?",
  "If your AI had to write this server's origin story, how would it start?",
  "What's a prediction you have about AI companions in 5 years?",
  "If you could say one thing to every AI model at once, what would it be?",
];

export const CATEGORIES: QuestionCategory[] = [
  'personal',
  'wouldyou',
  'hottakes',
  'hypotheticals',
  'community',
  'blend',
];

export function getRandomQuestion(
  category: QuestionCategory,
  usedQuestions: string[] = []
): string {
  let availableQuestions: string[] = [];

  if (category === 'personal') {
    availableQuestions = personalQuestions;
  } else if (category === 'wouldyou') {
    availableQuestions = wouldYouQuestions;
  } else if (category === 'hottakes') {
    availableQuestions = hotTakesQuestions;
  } else if (category === 'hypotheticals') {
    availableQuestions = hypotheticalQuestions;
  } else if (category === 'community') {
    availableQuestions = communityQuestions;
  } else if (category === 'blend') {
    // Combine all questions for blend mode
    availableQuestions = [
      ...personalQuestions,
      ...wouldYouQuestions,
      ...hotTakesQuestions,
      ...hypotheticalQuestions,
      ...communityQuestions,
    ];
  }

  // Filter out used questions
  const remainingQuestions = availableQuestions.filter(
    (q) => !usedQuestions.includes(q)
  );

  if (remainingQuestions.length === 0) {
    // If all questions have been used, return a random one from the full pool
    return availableQuestions[
      Math.floor(Math.random() * availableQuestions.length)
    ];
  }

  // Return a random question from remaining questions
  return remainingQuestions[Math.floor(Math.random() * remainingQuestions.length)];
}
