// Hangman Game - Word Bank Data
export const CATEGORIES = ['Animals', 'Food', 'Movies', 'Places', 'Actions', 'Memes', 'Pop Culture', 'General'];

export interface HangmanWord {
  word: string;
  category: string;
}

export const WORD_BANK: HangmanWord[] = [
  // Animals (25 words)
  { word: 'ELEPHANT', category: 'Animals' },
  { word: 'GIRAFFE', category: 'Animals' },
  { word: 'RHINOCEROS', category: 'Animals' },
  { word: 'PLATYPUS', category: 'Animals' },
  { word: 'PENGUIN', category: 'Animals' },
  { word: 'CHEETAH', category: 'Animals' },
  { word: 'FLAMINGO', category: 'Animals' },
  { word: 'HEDGEHOG', category: 'Animals' },
  { word: 'OCTOPUS', category: 'Animals' },
  { word: 'PORCUPINE', category: 'Animals' },
  { word: 'SLOTH', category: 'Animals' },
  { word: 'BADGER', category: 'Animals' },
  { word: 'MEERKAT', category: 'Animals' },
  { word: 'ALPACA', category: 'Animals' },
  { word: 'QUOKKA', category: 'Animals' },
  { word: 'WOMBAT', category: 'Animals' },
  { word: 'KOALA', category: 'Animals' },
  { word: 'LEMUR', category: 'Animals' },
  { word: 'IGUANA', category: 'Animals' },
  { word: 'RAVEN', category: 'Animals' },
  { word: 'PEACOCK', category: 'Animals' },
  { word: 'HYENA', category: 'Animals' },
  { word: 'ARMADILLO', category: 'Animals' },
  { word: 'ANTEATER', category: 'Animals' },
  { word: 'JAGUAR', category: 'Animals' },

  // Food (25 words)
  { word: 'SPAGHETTI', category: 'Food' },
  { word: 'BURRITO', category: 'Food' },
  { word: 'CHEESECAKE', category: 'Food' },
  { word: 'CROISSANT', category: 'Food' },
  { word: 'PANCAKE', category: 'Food' },
  { word: 'BROCCOLI', category: 'Food' },
  { word: 'AVOCADO', category: 'Food' },
  { word: 'PINEAPPLE', category: 'Food' },
  { word: 'WATERMELON', category: 'Food' },
  { word: 'STRAWBERRY', category: 'Food' },
  { word: 'BLUEBERRY', category: 'Food' },
  { word: 'ASPARAGUS', category: 'Food' },
  { word: 'CAULIFLOWER', category: 'Food' },
  { word: 'ARTICHOKE', category: 'Food' },
  { word: 'EGGPLANT', category: 'Food' },
  { word: 'CUCUMBER', category: 'Food' },
  { word: 'ZUCCHINI', category: 'Food' },
  { word: 'SPINACH', category: 'Food' },
  { word: 'KETCHUP', category: 'Food' },
  { word: 'MUSTARD', category: 'Food' },
  { word: 'WASABI', category: 'Food' },
  { word: 'TOFU', category: 'Food' },
  { word: 'HUMMUS', category: 'Food' },
  { word: 'NACHO', category: 'Food' },
  { word: 'TACO', category: 'Food' },

  // Movies (25 words)
  { word: 'INCEPTION', category: 'Movies' },
  { word: 'AVATAR', category: 'Movies' },
  { word: 'TITANIC', category: 'Movies' },
  { word: 'GLADIATOR', category: 'Movies' },
  { word: 'FROZEN', category: 'Movies' },
  { word: 'AVENGERS', category: 'Movies' },
  { word: 'JAWS', category: 'Movies' },
  { word: 'SHREK', category: 'Movies' },
  { word: 'HAIRSPRAY', category: 'Movies' },
  { word: 'GREASE', category: 'Movies' },
  { word: 'PHANTOM', category: 'Movies' },
  { word: 'BATMAN', category: 'Movies' },
  { word: 'SUPERMAN', category: 'Movies' },
  { word: 'IRONMAN', category: 'Movies' },
  { word: 'THOR', category: 'Movies' },
  { word: 'HULK', category: 'Movies' },
  { word: 'SPIDERMAN', category: 'Movies' },
  { word: 'DUNE', category: 'Movies' },
  { word: 'MATRIX', category: 'Movies' },
  { word: 'TERMINATOR', category: 'Movies' },
  { word: 'PREDATOR', category: 'Movies' },
  { word: 'ALIEN', category: 'Movies' },
  { word: 'JURASSIC', category: 'Movies' },
  { word: 'TRANSFORMER', category: 'Movies' },
  { word: 'DEADPOOL', category: 'Movies' },

  // Places (25 words)
  { word: 'PARIS', category: 'Places' },
  { word: 'TOKYO', category: 'Places' },
  { word: 'LONDON', category: 'Places' },
  { word: 'SYDNEY', category: 'Places' },
  { word: 'DUBAI', category: 'Places' },
  { word: 'CAIRO', category: 'Places' },
  { word: 'MOSCOW', category: 'Places' },
  { word: 'ISTANBUL', category: 'Places' },
  { word: 'AMSTERDAM', category: 'Places' },
  { word: 'BARCELONA', category: 'Places' },
  { word: 'SINGAPORE', category: 'Places' },
  { word: 'BANGKOK', category: 'Places' },
  { word: 'HONGKONG', category: 'Places' },
  { word: 'PRAGUE', category: 'Places' },
  { word: 'VENICE', category: 'Places' },
  { word: 'TAHITI', category: 'Places' },
  { word: 'ICELAND', category: 'Places' },
  { word: 'NORWAY', category: 'Places' },
  { word: 'GREENLAND', category: 'Places' },
  { word: 'ALASKA', category: 'Places' },
  { word: 'HAWAII', category: 'Places' },
  { word: 'BAHAMAS', category: 'Places' },
  { word: 'CANCUN', category: 'Places' },
  { word: 'MALDIVES', category: 'Places' },
  { word: 'BALI', category: 'Places' },

  // Actions (25 words)
  { word: 'SKATEBOARD', category: 'Actions' },
  { word: 'SKYDIVE', category: 'Actions' },
  { word: 'SNOWBOARD', category: 'Actions' },
  { word: 'ROLLERBLADE', category: 'Actions' },
  { word: 'CARTWHEEL', category: 'Actions' },
  { word: 'HANDSTAND', category: 'Actions' },
  { word: 'SOMERSAULT', category: 'Actions' },
  { word: 'PARKOUR', category: 'Actions' },
  { word: 'BACKFLIP', category: 'Actions' },
  { word: 'MOONWALK', category: 'Actions' },
  { word: 'TWERK', category: 'Actions' },
  { word: 'BREAKDANCE', category: 'Actions' },
  { word: 'JUGGLE', category: 'Actions' },
  { word: 'TIGHTROPE', category: 'Actions' },
  { word: 'TRAPEZE', category: 'Actions' },
  { word: 'TRAMPOLINE', category: 'Actions' },
  { word: 'RAPPEL', category: 'Actions' },
  { word: 'ABSEIL', category: 'Actions' },
  { word: 'WINDSURFING', category: 'Actions' },
  { word: 'SKATEBOARD', category: 'Actions' },
  { word: 'SNOWSKATE', category: 'Actions' },
  { word: 'MOUNTAINEER', category: 'Actions' },
  { word: 'FREESTYLE', category: 'Actions' },
  { word: 'HELICOPTER', category: 'Actions' },
  { word: 'SURFING', category: 'Actions' },

  // Memes (25 words)
  { word: 'RICKROLL', category: 'Memes' },
  { word: 'DABBING', category: 'Memes' },
  { word: 'YEET', category: 'Memes' },
  { word: 'BRUH', category: 'Memes' },
  { word: 'STONKS', category: 'Memes' },
  { word: 'DIAMOND', category: 'Memes' },
  { word: 'HODL', category: 'Memes' },
  { word: 'DOGECOIN', category: 'Memes' },
  { word: 'GORILLA', category: 'Memes' },
  { word: 'PENGUIN', category: 'Memes' },
  { word: 'SHIBA', category: 'Memes' },
  { word: 'DOGE', category: 'Memes' },
  { word: 'WOJAK', category: 'Memes' },
  { word: 'CHAD', category: 'Memes' },
  { word: 'SIMP', category: 'Memes' },
  { word: 'BONK', category: 'Memes' },
  { word: 'OOMPA', category: 'Memes' },
  { word: 'AMOGUS', category: 'Memes' },
  { word: 'SUS', category: 'Memes' },
  { word: 'NOOBMASTER', category: 'Memes' },
  { word: 'PWNED', category: 'Memes' },
  { word: 'LOLCAT', category: 'Memes' },
  { word: 'TROLLFACE', category: 'Memes' },
  { word: 'PEPE', category: 'Memes' },
  { word: 'VIBING', category: 'Memes' },

  // Pop Culture (25 words)
  { word: 'BEYONCE', category: 'Pop Culture' },
  { word: 'TAYLOR', category: 'Pop Culture' },
  { word: 'SHAKIRA', category: 'Pop Culture' },
  { word: 'DRAKE', category: 'Pop Culture' },
  { word: 'KANYE', category: 'Pop Culture' },
  { word: 'RIHANNA', category: 'Pop Culture' },
  { word: 'ADELE', category: 'Pop Culture' },
  { word: 'BILLIE', category: 'Pop Culture' },
  { word: 'DWAYNE', category: 'Pop Culture' },
  { word: 'OPRAH', category: 'Pop Culture' },
  { word: 'NETFLIX', category: 'Pop Culture' },
  { word: 'SPOTIFY', category: 'Pop Culture' },
  { word: 'YOUTUBE', category: 'Pop Culture' },
  { word: 'TIKTOK', category: 'Pop Culture' },
  { word: 'SNAPCHAT', category: 'Pop Culture' },
  { word: 'INSTAGRAM', category: 'Pop Culture' },
  { word: 'TWITTER', category: 'Pop Culture' },
  { word: 'DISCORD', category: 'Pop Culture' },
  { word: 'TWITCH', category: 'Pop Culture' },
  { word: 'FORTNITE', category: 'Pop Culture' },
  { word: 'MINECRAFT', category: 'Pop Culture' },
  { word: 'VALORANT', category: 'Pop Culture' },
  { word: 'POKEMON', category: 'Pop Culture' },
  { word: 'NINTENDO', category: 'Pop Culture' },
  { word: 'XBOX', category: 'Pop Culture' },

  // General (35 words)
  { word: 'RAINBOW', category: 'General' },
  { word: 'THUNDER', category: 'General' },
  { word: 'LIGHTNING', category: 'General' },
  { word: 'FIREFLY', category: 'General' },
  { word: 'BUTTERFLY', category: 'General' },
  { word: 'DRAGONFLY', category: 'General' },
  { word: 'CONSTELLATION', category: 'General' },
  { word: 'GALAXY', category: 'General' },
  { word: 'UNIVERSE', category: 'General' },
  { word: 'DIMENSION', category: 'General' },
  { word: 'TELESCOPE', category: 'General' },
  { word: 'MICROSCOPE', category: 'General' },
  { word: 'KALEIDOSCOPE', category: 'General' },
  { word: 'PERISCOPE', category: 'General' },
  { word: 'HOROSCOPE', category: 'General' },
  { word: 'ZODIAC', category: 'General' },
  { word: 'ALCHEMY', category: 'General' },
  { word: 'MYSTICAL', category: 'General' },
  { word: 'WIZARD', category: 'General' },
  { word: 'SORCERER', category: 'General' },
  { word: 'ENCHANTED', category: 'General' },
  { word: 'SPELLBOOK', category: 'General' },
  { word: 'GRIMOIRE', category: 'General' },
  { word: 'POTION', category: 'General' },
  { word: 'DRAGON', category: 'General' },
  { word: 'PHOENIX', category: 'General' },
  { word: 'UNICORN', category: 'General' },
  { word: 'PEGASUS', category: 'General' },
  { word: 'MINOTAUR', category: 'General' },
  { word: 'KRAKEN', category: 'General' },
  { word: 'CHIMERA', category: 'General' },
  { word: 'GARGOYLE', category: 'General' },
  { word: 'CENTAUR', category: 'General' },
  { word: 'SPHINX', category: 'General' },
  { word: 'GOLEM', category: 'General' },
];

export function getRandomWord(): HangmanWord {
  return WORD_BANK[Math.floor(Math.random() * WORD_BANK.length)];
}
